mqtt:
  enabled: false
go2rtc:
  streams:
    kamera_flur:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.kamera_flur

cameras:
  kamera_flur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamera_flur?video
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect

detectors:
  coral:
    type: edgetpu
    device: usb