---
mqtt:
  enabled: true
  host: 10.182.1.68
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: KRYyIBaf4of

go2rtc:
  streams:
    kamera_flur:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.kamera_flur
    kamera_buro:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.kamera_buro
    kamera_schlafzimmer:
      - rtsp://rtsp:h9LqiF5g@10.182.1.226:554/av_stream/ch0
    kamera_wohnzimmer:
      - rtsp://10.182.1.106/live0
    roborock:
      - roborock://mqtt-eu-2.roborock.com:8883?u=2I9mZWOH7LgxmGcIQG2S0E&s=fqW8Qr&k=rn9WI8OJ&did=5zt94riLsEgRJEl1GcaD1V&key=whE66waAZLFKZPo4&pin=

cameras:
  kamera_flur:
    enabled: True
    detect:
      width: 1280
      height: 720
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.182.1.68:8554/kamera_flur
          input_args: preset-rtsp-restream
          roles:
            - detect
  kamera_buro:
    enabled: True
    detect:
      width: 1280
      height: 720
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.182.1.68:8554/kamera_buro
          input_args: preset-rtsp-restream
          roles:
            - detect
  kamera_schlafzimmer:
    enabled: True
    detect:
      width: 1280
      height: 720
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.182.1.68:8554/kamera_schlafzimmer
          input_args: preset-rtsp-restream
          roles:
            - detect
  kamera_wohnzimmer:
    enabled: True
    detect:
      width: 1280
      height: 720
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.182.1.68:8554/kamera_wohnzimmer
          input_args: preset-rtsp-restream
          roles:
            - detect

birdseye:
  enabled: True
  restream: False
  width: 1280
  height: 720
  quality: 8

objects:
  track:
    - person

detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.14
