homeassistant:
  packages: !include_dir_named packages
  legacy_templates: false
  allowlist_external_dirs:
    - /config/

script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include_dir_merge_named custom_configs/devices/input_selects/
input_boolean: !include_dir_merge_named custom_configs/devices/input_booleans/
input_text: !include_dir_merge_named custom_configs/devices/input_texts/
rest_command: !include_dir_merge_named custom_configs/devices/rest_commands/
sensor: !include_dir_merge_list custom_configs/devices/sensors/
camera: !include_dir_merge_list custom_configs/devices/cameras/
group: !include_dir_merge_list custom_configs/groups/
template: !include_dir_merge_list custom_configs/templates/
binary_sensor: !include_dir_merge_list custom_configs/devices/binary_sensors/
#homekit: !include_dir_merge_list custom_configs/homekit/
#telegram_bot: !include_dir_merge_list custom_configs/telegram_bot/
proximity: !include_dir_merge_list custom_configs/proximity/
rest: !include_dir_merge_list custom_configs/rest/
switch: !include_dir_merge_list custom_configs/devices/switches/
conversation: !include_dir_merge_list custom_configs/conversation/
#alert: !include_dir_merge_named custom_configs/alerts/
intent_script: !include_dir_merge_list custom_configs/intents/
shell_command: !include_dir_merge_list custom_configs/shell_commands/
automation: !include automations.yaml

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
