global:
  instanceName: HA
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: mqtt://10.182.101:1883
  mqttOptions:
    username: !secret mqtt_user
    password: !secret mqtt_password
  discoveryPrefix: homeassistant
  sendAttributes: true
  sendMqttRoom: true