action:
- data: {}
  metadata: {}
  service: script.1699263855216
alias: '[Admin] Zigbee2MQTT Restart Nightly'
condition: []
description: ''
id: '1713443188220'
mode: single
trigger:
- at: 00:00:00
  platform: time
