actions:
- choose:
  - conditions:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    sequence:
    - action: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_wohnzimmer
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_schlafzimmer
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_flur
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_kuche
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_buro
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_badezimmer
  - conditions:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    sequence:
    - action: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_wohnzimmer
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_schlafzimmer
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_flur
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_kuche
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_buro
        - switch.adaptive_lighting_sleep_mode_adaptive_lighting_badezimmer
alias: '[Core] Adaptive Lighting: Sleep Mode Sync'
conditions: []
description: Toggles Adaptive Lighting sleep mode based on input_boolean.night_mode.
id: '1769616795004'
mode: single
triggers:
- entity_id: input_boolean.night_mode
  trigger: state
