action:
- service: homeassistant.restart
alias: '[HA] Restart'
description: ''
id: ha_restart
max_exceeded: silent
trigger:
- event_data:
    action: restart_ha
  event_type: mobile_app_notification_action
  platform: event
