action:
- action: system_log.write
  data:
    level: critical
    logger: '{{ this.entity_id }}

      '
    message: '**** HOME ASSISTANT STOP ****'
- if:
  - condition: state
    entity_id: input_boolean.alerts_ha
    state: 'on'
  then:
  - action: notify.mobile_app_iphone_von_florian
    data:
      data:
        presentation_options:
        - alert
        - badge
        push:
          badge: 1
          interruption-level: time-sensitive
          sound: none
      message: Home Assistant has Stopped
      title: Home Assistant Stopped
alias: '[HA] Shutdown'
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1717347835711'
trigger:
- event: shutdown
  platform: homeassistant
