action:
- data: {}
  metadata: {}
  service: input_number.decrement
  target:
    entity_id: input_number.spulmaschinentabs
alias: "[NFC Tag] Sp\xFClmaschinentabs"
condition: []
description: ''
id: '1718550657718'
mode: single
trigger:
- platform: tag
  tag_id: spuelmaschinentabs
