action:
- data:
    date: '{{ states(''sensor.date'') }}'
  service: input_datetime.set_datetime
  target:
    entity_id: input_datetime.wassertank_aufgefullt
alias: "[NFC Tag] Staubsauger Wassertank nachgef\xFCllt"
condition: []
description: ''
id: '1718562692032'
mode: single
trigger:
- platform: tag
  tag_id: staubsauger_wassertank
