action:
- data: {}
  metadata: {}
  service: input_number.decrement
  target:
    entity_id: input_number.waschmaschinentabs
alias: '[NFC Tag] Waschmaschinentabs'
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1718550615267'
mode: single
trigger:
- platform: tag
  tag_id: waschmaschinentabs
