action:
- data:
    payload: 'false'
    topic: zigbee2mqtt/bridge/config/permit_join
  service: mqtt.publish
- data:
    entity_id: timer.z2m_permit_join
  service: timer.cancel
alias: '[Zigbee2MQTT] Disable Z2M Join'
description: ''
id: '1717147845731'
trigger:
  entity_id: input_boolean.z2m_permit_join
  platform: state
  to: 'off'
