action:
- data:
    create_file: true
    parse_config: true
  metadata: {}
  service: watchman.report
alias: Admin - Watchman
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1713209693062'
mode: single
trigger:
- hours: '3'
  platform: time_pattern
