action:
- service: readme.generate
alias: Admin - Generate README.md
condition: []
description: ''
id: a7c427e6-ce03-49eb-9a23-c5bbe7625aa4
initial_state: true
trigger:
- at: 05:00:00
  platform: time
