actions:
- action: notify.all_iphones
  data:
    data:
      actions:
      - action: URI
        title: Resolve now!
        uri: /lovelace/home
    message: "\U0001F511 Authentication Required"
    title: Alexa Media Player Integration
alias: Alexa Media Player Authentication Required
conditions: []
description: ''
id: alexa_media_player_authentication_required
triggers:
- event_type: alexa_media_relogin_required
  trigger: event
