action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - anyoneHomeOn
    sequence:
    - data: {}
      service: switch.turn_on
      target:
        device_id: 9d14dca47a5773d55c5f7f9d16c58476
  - conditions:
    - condition: trigger
      id:
      - doorOpenOn
    - condition: template
      enabled: true
      value_template: '{{ is_state_attr(''media_player.spotify_florian'', ''source'',
        ''iPhone'') }}'
    - condition: template
      enabled: true
      value_template: '{{ is_state(''media_player.spotify_florian'', ''playing'')
        }}'
    sequence:
    - data:
        message: Ich habe die Musik von deinem iPhone auf Sonos Ray gestellt
        title: "Willkommen Zuhause \U0001F3E0"
      service: notify.home_ai
    - data:
        source: Spotify Connect
      service: media_player.select_source
      target:
        entity_id: media_player.sonos_ray_wohnzimmer
    - data:
        source: Sonos Ray
      service: media_player.select_source
      target:
        entity_id: media_player.spotify_florian
    - data: {}
      service: media_player.media_play
      target:
        entity_id: media_player.sonos_ray_wohnzimmer
  - conditions:
    - condition: trigger
      id:
      - doorOpenOn
    - condition: template
      enabled: true
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.person.florian_wartner.last_changed))
        < 10 }}'
    sequence:
    - data:
        volume_level: 0.25
      metadata: {}
      service: media_player.volume_set
      target:
        device_id: 5d251a0a20f76a8251bbdb9e1b1b0178
    - data: {}
      metadata: {}
      service: script.willkommen_florian
alias: Ankommen
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.guestmode
    state: 'off'
description: ''
id: '1691741828322'
mode: single
trigger:
- enabled: true
  entity_id:
  - binary_sensor.aqara_contact_wohnungstur_contact
  for:
    hours: 0
    minutes: 0
    seconds: 2
  from: 'on'
  id: doorOpenOn
  platform: state
  to: 'off'
- entity_id:
  - sensor.people_home
  id: anyoneHomeOn
  platform: state
  to: '1'
