actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - timeOn
    sequence:
    - action: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.dashboard_flur_bildschirm
        - switch.lenovo_tab_m10_bildschirm
alias: Aufstehen
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1692310400644'
mode: single
triggers:
- at: 08:30:00
  id: timeOn
  trigger: time
