action:
- data:
    payload: '{"text":"Download speed is {{ states.sensor.speedtest_download.state}}  Mbp/s","icon":"download","pushIcon":0,"repeat":1,"textCase":2,"textOffset":33}'
    qos: '0'
    retain: false
    topic: awtrix_wohnzimmer/custom/speedtest_down
  metadata: {}
  service: mqtt.publish
- data:
    payload: '{"text":"Upload speed is {{ states.sensor.speedtest_upload.state}}  Mbp/s","icon":"upload","pushIcon":0,"repeat":1,"textCase":2,"textOffset":33}'
    qos: '0'
    retain: false
    topic: awtrix_wohnzimmer/custom/speedtest_up
  metadata: {}
  service: mqtt.publish
alias: 'AWTRIX: Speedtest'
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1715341229281'
mode: single
trigger:
- minutes: /10
  platform: time_pattern
