actions:
- action: homeassistant.update_entity
  data:
    entity_id:
    - image.bambu_lab_a1_titelbild
alias: Bambu Lab A1 Image Reload
conditions: []
description: ''
id: '1730139795585'
mode: single
triggers:
- entity_id:
  - sensor.bambu_lab_a1_aktueller_arbeitsschritt
  to: printing
  trigger: state
