actions:
- action: battery_notes.set_battery_replaced
  data:
    device_id: '{{ trigger.event.data.device_id }}'
    source_entity_id: '{{ trigger.event.data.source_entity_id }}'
alias: Battery Replaced
conditions: []
description: Battery Replaced
id: '1731317900823'
mode: queued
triggers:
- event_type: battery_notes_battery_increased
  trigger: event
