actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - bkwSunPower
    sequence:
    - action: notify.florian_notify
      data:
        data:
          actions:
          - action: IOS_BKW_WASCHMASCHINE_AN
            icon: sfsymbols:power
            title: Waschmaschine
          - action: IOS_BKW_SPUELMASCHINE_AN
            icon: sfsymbols:power
            title: "Sp\xFChlmaschine"
          - action: IOS_BKW_ALLES_AN
            icon: sfsymbols:power
            title: Beides
        message: "Du erzeugst gerade so viel Energie, du k\xF6nntest doch glatt die\
          \ Waschmaschine oder die Sp\xFClmaschine laufen lassen! Soll ich die Steckdosen\
          \ einschalten? (Ignoriere die Temperatur in der K\xFCche)"
        title: "\u2600\uFE0F Die Sonne scheint pr\xE4chtig!"
      metadata: {}
  - conditions:
    - condition: trigger
      id:
      - bkwIOSWMAn
    sequence:
    - device_id: 3c45a70c459e2e66b166dca5891180c6
      domain: switch
      entity_id: eb4d372310f986822d024a05f2007c03
      type: turn_on
  - conditions:
    - condition: trigger
      id:
      - bkwIOSSMAn
    sequence:
    - device_id: 4a05cd597a16be48ba279a90d1ba5c18
      domain: switch
      entity_id: 6a36fb96527589eaed3672a9978a3393
      type: turn_on
  - conditions:
    - condition: trigger
      id:
      - bkwIOSALLESAn
    sequence:
    - device_id: 4a05cd597a16be48ba279a90d1ba5c18
      domain: switch
      entity_id: 6a36fb96527589eaed3672a9978a3393
      type: turn_on
    - device_id: 3c45a70c459e2e66b166dca5891180c6
      domain: switch
      entity_id: eb4d372310f986822d024a05f2007c03
      type: turn_on
alias: 'BKW: Maschinen laufen lassen Notification'
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.nicht_storen
    state: 'off'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - above: 0.3
    condition: numeric_state
    entity_id: sensor.people_home
description: ''
id: '1712829051695'
mode: single
triggers:
- above: 330
  entity_id:
  - sensor.shelly_bkw_power
  for:
    hours: 0
    minutes: 5
    seconds: 0
  id: bkwSunPower
  trigger: numeric_state
- event_data:
    action: IOS_BKW_WASCHMASCHINE_AN
  event_type: mobile_app_notification_action
  id: bkwIOSWMAn
  trigger: event
- event_data:
    action: IOS_BKW_SPUELMASCHINE_AN
  event_type: mobile_app_notification_action
  id: bkwIOSSMAn
  trigger: event
- event_data:
    action: IOS_BKW_ALLES_AN
  event_type: mobile_app_notification_action
  id: bkwIOSALLESAn
  trigger: event
