actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - couchFrei
    sequence:
    - action: media_player.media_pause
      data: {}
      metadata: {}
      target:
        device_id: 67feb204d2fca3cfd31e143defa33fe5
  - conditions:
    - condition: trigger
      id:
      - couchBelegt
    sequence:
    - action: remote.send_command
      data:
        command: play
      metadata: {}
      target:
        device_id: 67feb204d2fca3cfd31e143defa33fe5
alias: Couch
conditions:
- condition: and
  conditions:
  - above: 0
    condition: numeric_state
    entity_id: sensor.people_home
  - condition: state
    entity_id: input_boolean.movietime
    state: 'on'
description: ''
id: '1728905439373'
mode: single
triggers:
- device_id: 779a3e27762696ab42d6562bf3501934
  domain: binary_sensor
  entity_id: fc3bf20b4daf944d19c71e62a29723f8
  id: couchFrei
  trigger: device
  type: not_occupied
- device_id: 779a3e27762696ab42d6562bf3501934
  domain: binary_sensor
  entity_id: fc3bf20b4daf944d19c71e62a29723f8
  id: couchBelegt
  trigger: device
  type: occupied
