action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - currentPlayerChange
    sequence:
    - data:
        value: '{{ states(''sensor.current_media_player'') }}'
      service: input_text.set_value
      target:
        entity_id: input_text.last_media_player
  - conditions:
    - condition: trigger
      id:
      - playPauseTrigger
    sequence:
    - data: {}
      enabled: true
      metadata: {}
      service: media_player.media_play_pause
      target:
        entity_id: '{{ states(''input_text.last_media_player'') }}

          '
  - conditions:
    - condition: trigger
      id:
      - nextTrigger
    sequence:
    - data: {}
      metadata: {}
      service: media_player.media_next_track
      target:
        entity_id: '{{ states(''input_text.last_media_player'') }}

          '
  - conditions:
    - condition: trigger
      id:
      - prevTrigger
    sequence:
    - data: {}
      service: media_player.media_previous_track
      target:
        entity_id: '{{ states(''input_text.last_media_player'') }}

          '
alias: Current Media Player Controls
condition: []
description: ''
id: '1718970747624'
mode: single
trigger:
- entity_id:
  - sensor.current_media_player
  id: currentPlayerChange
  platform: state
  to: null
- enabled: true
  entity_id:
  - input_button.play_pause
  id: playPauseTrigger
  platform: state
  to: null
- enabled: true
  entity_id:
  - input_button.next_track
  id: nextTrigger
  platform: state
  to: null
- enabled: true
  entity_id:
  - input_button.prev_track
  id: prevTrigger
  platform: state
  to: null
