actions:
- action: notify.florian_notify
  data:
    data:
      actions:
      - action: URI
        title: View Image
        uri: "{% if trigger.to_state.attributes.match is defined %}\n  http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}\n\
          {% elif trigger.to_state.attributes.unknown is defined %}\n   http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.unknown.filename}}?box=true&token={{trigger.to_state.attributes.token}}\n\
          {% endif %}"
      attachment:
        url: "{% if trigger.to_state.attributes.match is defined %}\n  http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}\n\
          {% elif trigger.to_state.attributes.unknown is defined %}\n   http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.unknown.filename}}?box=true&token={{trigger.to_state.attributes.token}}\n\
          {% endif %}"
    message: "{% if trigger.to_state.attributes.match is defined %}\n  {{trigger.to_state.attributes.friendly_name}}\
      \ is near the {{trigger.to_state.state}} @ {{trigger.to_state.attributes.match.confidence}}%\
      \ by {{trigger.to_state.attributes.match.detector}}:{{trigger.to_state.attributes.match.type}}\
      \ taking {{trigger.to_state.attributes.attempts}} attempt(s) @ {{trigger.to_state.attributes.duration}}\
      \ sec\n{% elif trigger.to_state.attributes.unknown is defined %}\n  unknown\
      \ is near the {{trigger.to_state.state}} @ {{trigger.to_state.attributes.unknown.confidence}}%\
      \ by {{trigger.to_state.attributes.unknown.detector}}:{{trigger.to_state.attributes.unknown.type}}\
      \ taking {{trigger.to_state.attributes.attempts}} attempt(s) @ {{trigger.to_state.attributes.duration}}\
      \ sec\n{% endif %}"
alias: Double Take
conditions:
- condition: template
  value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
description: ''
id: '1732631390595'
max: 10
mode: parallel
triggers:
- entity_id:
  - sensor.double_take_florian
  trigger: state
- entity_id: sensor.double_take_unknown
  trigger: state
