action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - waterBadezimmerOn
    sequence:
    - delay:
        hours: 0
        milliseconds: 0
        minutes: 0
        seconds: 10
    - data:
        volume_level: 0.4
      service: media_player.volume_set
      target:
        entity_id: media_player.echo_badezimmer
    - data:
        media_content_id: shuffle 37i9dQZF1DWSqmBTGDYngZ
        media_content_type: SPOTIFY
      metadata: {}
      service: media_player.play_media
      target:
        entity_id: media_player.echo_badezimmer
  - conditions:
    - condition: trigger
      id:
      - mmwaveDuschenAus
    sequence:
    - data: {}
      service: media_player.media_stop
      target:
        entity_id: media_player.echo_badezimmer
    - data:
        hvac_mode: 'off'
      service: climate.set_hvac_mode
      target:
        entity_id: climate.heizung_badezimmer
    - data: {}
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.duschen_besetzt
  - conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - luftfeuchtigkeitBadezimmerHoch
      - condition: state
        entity_id: binary_sensor.fenster_badezimmer
        state: 'off'
    sequence:
    - data:
        data:
          method: all
          type: announce
        message: "Bitte \xF6ffne doch das Fenster im Badezimmer. Oder m\xF6chtest\
          \ du ein kleines Feuchtbiotop Zuhause haben?"
        target:
        - media_player.echo_badezimmer
        - media_player.echo_schlafzimmer
        - media_player.echo_schlafzimmer
        title: "L\xFCften nicht vergessen"
      service: notify.alexa_media
alias: Duschen
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1700300672837'
mode: single
trigger:
- entity_id:
  - binary_sensor.aqara_water_badezimmer_water_leak
  from: 'off'
  id: waterBadezimmerOn
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.aqara_water_badezimmer_water_leak
  from: 'on'
  id: waterBadezimmerOff
  platform: state
  to: 'off'
- entity_id:
  - binary_sensor.mmwave_badezimmer
  from: 'on'
  id: mmwaveDuschenAus
  platform: state
  to: 'off'
- above: 70
  entity_id:
  - sensor.badezimmer_luftfeuchtigkeit
  for:
    hours: 0
    minutes: 20
    seconds: 0
  id: luftfeuchtigkeitBadezimmerHoch
  platform: numeric_state
