action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - florianVorWarnstufe
      - florianAktuelleWarnstufe
    sequence:
    - data:
        message: Es scheint eine neue Wetterwarnung vom Deutschen Wetterdienst zu
          geben. Pass besser auf.
        title: "\u26A0\uFE0F Es gibt eine Wetterwarnung"
      service: notify.mobile_app_iphone_von_florian
  - conditions:
    - condition: trigger
      id:
      - steffiVorWarnstufe
      - steffiAktuelleWarnstufe
    sequence:
    - data:
        message: Es scheint eine neue Wetterwarnung vom Deutschen Wetterdienst zu
          geben. Pass besser auf.
        title: "\u26A0\uFE0F Es gibt eine Wetterwarnung"
      service: notify.mobile_app_22041219ny
alias: DWD Warnung Notification Mobile
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1720006679551'
mode: single
trigger:
- above: 0
  entity_id:
  - sensor.stadt_lubeck_vorwarnstufe
  id: florianVorWarnstufe
  platform: numeric_state
- above: 0
  entity_id:
  - sensor.stadt_lubeck_aktuelle_warnstufe
  id: florianAktuelleWarnstufe
  platform: numeric_state
- above: 0
  entity_id:
  - sensor.hamburg_eimsbuttel_vorwarnstufe
  id: steffiVorWarnstufe
  platform: numeric_state
- above: 0
  entity_id:
  - sensor.hamburg_eimsbuttel_aktuelle_warnstufe
  id: steffiAktuelleWarnstufe
  platform: numeric_state
