actions:
- action: switch.turn_on
  target:
    entity_id: switch.adguard_home_filterung
alias: Enable AdGuard Filtering in the Morning
conditions: []
description: ''
id: '1745140339650'
triggers:
- at: 07:00:00
  trigger: time
