actions:
- action: light.turn_on
  data:
    brightness_pct: 60
    transition: 1
  target:
    entity_id: light.lightener_flur
- continue_on_timeout: true
  timeout: 00:05:00
  wait_for_trigger:
  - entity_id: binary_sensor.hlk_flur_belegung
    from: 'on'
    to: 'off'
    trigger: state
- action: light.turn_off
  data:
    transition: 2
  target:
    entity_id: light.lightener_flur
alias: "Flur: Licht an wenn T\xFCr auf"
conditions:
- condition: and
  conditions:
  - after: sunset
    after_offset: +01:00:00
    before: sunrise
    condition: sun
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - below: 10
    condition: numeric_state
    entity_id: sensor.awtrix_ed6030_illuminance
description: "Automatisches Flur-Licht bei T\xFCr\xF6ffnung w\xE4hrend Dunkelheit\
  \ mit Auto-Aus Timer"
id: '1669632865548'
mode: single
triggers:
- entity_id: binary_sensor.aqara_contact_wohnungstur_contact
  for:
    seconds: 1
  from: 'off'
  to: 'on'
  trigger: state
