action:
- data:
    data:
      photo:
      - caption: Eine {{trigger.payload_json["after"]["label"]}} wurde von  {{trigger.payload_json["after"]["camera"]}}
          erfasst.
        url: https://ha.wartner.cloud/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?box=1
    message: "Eine {{trigger.payload_json[\"after\"][\"label\"]}} wurde von \n   \
      \       {{trigger.payload_json[\"after\"][\"camera\"]}} erfasst."
    title: Jemand befindet sich in deiner Wohnung
  service: notify.home_ai
alias: 'Frigate: Person erfasst'
condition:
- below: 1
  condition: numeric_state
  enabled: true
  entity_id: sensor.people_home
- condition: state
  entity_id: input_boolean.nicht_storen
  state: 'off'
description: ''
id: '1713084625685'
mode: single
trigger:
- device_id: 58d5751a575da55de44805455265fbe1
  domain: binary_sensor
  entity_id: 88626c253fc68a961eda8090dd829438
  platform: device
  type: occupied
- device_id: 328d9642040f6cf98392dcf5e15227d7
  domain: binary_sensor
  entity_id: 51cac45251a7a5294e47082835a20b4a
  platform: device
  type: occupied
