actions:
- action: notify.whatsapp_iryna
  data:
    message: '{{ states(''sensor.good_morning_iryna'') }}'
  metadata: {}
alias: Good Morning Iryna WhatsApp
conditions: []
description: ''
id: '1743600218230'
mode: single
triggers:
- at: '{{ states(''sensor.random_morning_action_time'') }}'
  trigger: time
