actions:
- action: template.reload
  data: {}
  metadata: {}
- delay:
    hours: 0
    milliseconds: 0
    minutes: 0
    seconds: 10
- action: notify.whatsapp_iryna
  data:
    message: '{{ states(''sensor.good_morning_iryna'') }}'
  metadata: {}
alias: Good Morning Iryna WhatsApp
conditions: []
description: ''
id: '1743600218230'
mode: single
triggers:
- at: 06:30:00
  trigger: time
