action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - balkonDoorOpen
    sequence:
    - if:
      - condition: state
        entity_id: climate.eve_heizung_wohnzimmer
        state: heat
      then:
      - device_id: b4caf944bee99395e23b319efe0618b7
        domain: climate
        entity_id: 163bf4ce33a250745098a4632c52a7e3
        hvac_mode: 'off'
        type: set_hvac_mode
  - conditions:
    - condition: trigger
      id:
      - balkonDoorClosed
    sequence:
    - if:
      - condition: state
        entity_id: climate.eve_heizung_wohnzimmer
        state: 'off'
      then:
      - device_id: b4caf944bee99395e23b319efe0618b7
        domain: climate
        entity_id: 163bf4ce33a250745098a4632c52a7e3
        hvac_mode: heat
        type: set_hvac_mode
alias: Heizung Kontrolle
condition: []
description: ''
id: '1726234446658'
mode: single
trigger:
- entity_id:
  - binary_sensor.aqara_contact_balkontur_contact
  id: balkonDoorOpen
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.aqara_contact_balkontur_contact
  id: balkonDoorClosed
  platform: state
  to: 'on'
