action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - alleHeizungenAus
    sequence:
    - if:
      - condition: or
        conditions:
        - condition: state
          entity_id: climate.heizung_badezimmer
          state: heat
        - condition: state
          entity_id: climate.heizung_wohnzimmer
          state: heat
        - condition: state
          entity_id: climate.heizung_schlafzimmer
          state: heat
        - condition: state
          entity_id: climate.heizung_buro
          state: heat
      then:
      - data:
          hvac_mode: 'off'
        service: climate.set_hvac_mode
        target:
          device_id:
          - 90ee15e301be363c6e674cb006400119
          - afd3d4982d793f98224ce76064298198
          - a71ccaedb801d2e7e89232f60fea1706
          - 5106942131c1dfe9055cba838a26b47b
      - data:
          message: Alle Heizungen wurden erfolgreich ausgeschaltet.
          title: "\u2139\uFE0F Alle Heizungen ausgeschaltet"
        service: notify.home_ai
  - conditions:
    - condition: trigger
      id:
      - alleHeizungenAn
    sequence:
    - if: []
      then:
      - data:
          hvac_mode: heat
        service: climate.set_hvac_mode
      - data:
          message: Alle Heizungen wurden erfolgreich eingeschaltet.
          title: "\u2139\uFE0F Alle Heizungen eingeschaltet"
        service: notify.home_ai
alias: Heizung Toggle
condition: []
description: ''
id: '1701773191392'
mode: single
trigger:
- entity_id:
  - input_boolean.heizung_toggle
  from: 'on'
  id: alleHeizungenAus
  platform: state
  to: 'off'
- entity_id:
  - input_boolean.heizung_toggle
  from: 'off'
  id: alleHeizungenAn
  platform: state
  to: 'on'
