action:
- choose:
  - alias: Heizung Badezimmer Aus
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - fensterBadezimmerAuf
      - condition: device
        device_id: 90ee15e301be363c6e674cb006400119
        domain: climate
        entity_id: 03daa9c5cdca12b2bf1eb23b40f1d940
        hvac_mode: heat
        type: is_hvac_mode
    sequence:
    - device_id: 90ee15e301be363c6e674cb006400119
      domain: climate
      entity_id: 03daa9c5cdca12b2bf1eb23b40f1d940
      hvac_mode: 'off'
      type: set_hvac_mode
  - alias: Heizung Schlafzimmer Aus
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - fensterSchlafzimmerAuf
      - condition: device
        device_id: a71ccaedb801d2e7e89232f60fea1706
        domain: climate
        entity_id: a499efc97a3a60b89a6cb823e8587346
        hvac_mode: heat
        type: is_hvac_mode
    sequence:
    - device_id: a71ccaedb801d2e7e89232f60fea1706
      domain: climate
      entity_id: a499efc97a3a60b89a6cb823e8587346
      hvac_mode: 'off'
      type: set_hvac_mode
  - alias: Heizung Wohnzimmer Aus
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - fensterWohnzimmerAuf
        - fensterWohnzimmer2Auf
      - condition: device
        device_id: 5106942131c1dfe9055cba838a26b47b
        domain: climate
        entity_id: 3faa59886c33a1ae38e91b758a6c7bd4
        hvac_mode: heat
        type: is_hvac_mode
    sequence:
    - device_id: 5106942131c1dfe9055cba838a26b47b
      domain: climate
      entity_id: 3faa59886c33a1ae38e91b758a6c7bd4
      hvac_mode: 'off'
      type: set_hvac_mode
alias: Heizung
condition: []
description: ''
id: '1701771967706'
mode: single
trigger:
- entity_id:
  - binary_sensor.fenster_badezimmer
  from: 'off'
  id: fensterBadezimmerAuf
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.fenster_schlafzimmer
  from: 'off'
  id: fensterSchlafzimmerAuf
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.fenster_wohnzimmer
  from: 'off'
  id: fensterWohnzimmerAuf
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.aqara_contact_balkontur_contact
  from: 'off'
  id: fensterWohnzimmer2Auf
  platform: state
  to: 'on'
