actions:
- action: counter.reset
  data: {}
  enabled: true
  target:
    entity_id:
    - counter.katzenklo_counter
- if:
  - after: 08:00:00
    before: '20:00:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  then:
  - action: vacuum.send_command
    data:
      command: set_custom_mode
      params: 104
    metadata: {}
    target:
      entity_id: vacuum.roborock_s7_maxv
  - action: vacuum.set_fan_speed
    data:
      fan_speed: '100'
    target:
      entity_id:
      - vacuum.roborock_s7_maxv
  - action: roborock.vacuum_clean_segment
    data:
      repeats: 1
      segments:
      - 20
    target:
      entity_id: vacuum.roborock_s7_maxv
alias: Katzenklo Counter Reset
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.staubsauger_reinigung_erlaubt
    state: 'on'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1710933790796'
mode: single
triggers:
- entity_id:
  - counter.katzenklo_counter
  to: '11'
  trigger: state
