action:
- delay:
    hours: 0
    milliseconds: 0
    minutes: 0
    seconds: 3
- data: {}
  service: counter.increment
  target:
    entity_id: counter.katzenklo_counter
alias: Katzenklo Counter Increase
condition: []
description: ''
id: '1710933026215'
mode: single
trigger:
- entity_id:
  - binary_sensor.aqara_contact_katzenklo_contact
  from: 'off'
  platform: state
  to: 'on'
