action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - kloAn
    sequence:
    - data: {}
      metadata: {}
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.klo_besetzt
  - conditions:
    - condition: trigger
      id:
      - kloAus
    sequence:
    - data: {}
      metadata: {}
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.klo_besetzt
alias: Klo Besetzt
condition: []
description: ''
id: '1718565264616'
mode: single
trigger:
- above: -5
  entity_id:
  - sensor.aqara_vibrate_katzenklo_angle_y
  id: kloAn
  platform: numeric_state
- below: -5
  entity_id:
  - sensor.aqara_vibrate_katzenklo_angle_y
  id: kloAus
  platform: numeric_state
