actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - washingMachineOffAfterTime
    sequence:
    - device_id: 3c45a70c459e2e66b166dca5891180c6
      domain: switch
      entity_id: eb4d372310f986822d024a05f2007c03
      type: turn_off
    - action: notify.florian_notify
      data:
        message: "Die W\xE4sche ist fertig."
        title: "\U0001F9FA W\xE4sche ist fertig"
  - conditions:
    - condition: trigger
      id:
      - dishWasherOffAfterTime
    sequence:
    - device_id: 4a05cd597a16be48ba279a90d1ba5c18
      domain: switch
      entity_id: 6a36fb96527589eaed3672a9978a3393
      type: turn_off
    - action: notify.florian_notify
      data:
        message: "Sp\xFClmaschine ist fertig."
        title: "\U0001F37D\uFE0F Geschirr ist sauber"
alias: "K\xFCche Steckdosen Power Management"
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1711970540815'
mode: single
triggers:
- entity_id:
  - sensor.steckdose_waschmaschine_energy_power
  for:
    hours: 0
    minutes: 2
    seconds: 0
  from: null
  id: washingMachineOffAfterTime
  to: '0'
  trigger: state
- entity_id:
  - sensor.steckdose_spuhlmaschine_energy_power
  for:
    hours: 0
    minutes: 2
    seconds: 0
  from: null
  id: dishWasherOffAfterTime
  to: '0'
  trigger: state
