action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - washingMachineOffAfterTime
    sequence:
    - device_id: 3c45a70c459e2e66b166dca5891180c6
      domain: switch
      entity_id: eb4d372310f986822d024a05f2007c03
      type: turn_off
    - data:
        message: "{{ [                 \"Waschmaschine ist fertig, bitte ausr\xE4\
          umen!\",                 \"Die W\xE4sche ist fertig, bitte aus der Maschine\
          \ holen.\",                 \"Zeit, die Waschmaschine auszur\xE4umen!\"\
          ,                 \"Waschmaschine ausr\xE4umen nicht vergessen!\",     \
          \            \"Die W\xE4sche wartet, bitte die Maschine leeren.\",     \
          \            \"Hol die W\xE4sche aus der Waschmaschine!\",             \
          \    \"Die Waschmaschine hat ihren Job getan, jetzt bist du dran.\",   \
          \              \"Bitte Waschmaschine ausr\xE4umen, die W\xE4sche ist fertig.\"\
          ,                 \"W\xE4sche aus der Waschmaschine nehmen nicht vergessen!\"\
          ,                 \"Waschmaschine ist fertig, W\xE4sche rausnehmen!\"  \
          \               ] | random }}"
        title: "\U0001F9FA W\xE4sche ist fertig"
      service: notify.mobile_app_iphone_von_florian
  - conditions:
    - condition: trigger
      id:
      - dishWasherOffAfterTime
    sequence:
    - device_id: 4a05cd597a16be48ba279a90d1ba5c18
      domain: switch
      entity_id: 6a36fb96527589eaed3672a9978a3393
      type: turn_off
    - data:
        message: "{{ [\n            \"Sp\xFClmaschine ist fertig, bitte ausr\xE4umen!\"\
          ,\n            \"Die Geschirrsp\xFClmaschine ist fertig, bitte leeren.\"\
          ,\n            \"Zeit, die Sp\xFClmaschine auszur\xE4umen!\",\n        \
          \    \"Sp\xFClmaschine ausr\xE4umen nicht vergessen!\",\n            \"\
          Das Geschirr wartet, bitte die Maschine leeren.\",\n            \"Hol das\
          \ Geschirr aus der Sp\xFClmaschine!\",\n            \"Die Sp\xFClmaschine\
          \ hat ihren Job getan, jetzt bist du dran.\",\n            \"Bitte Sp\xFC\
          lmaschine ausr\xE4umen, das Geschirr ist sauber.\",\n            \"Geschirr\
          \ aus der Sp\xFClmaschine nehmen nicht vergessen!\",\n            \"Sp\xFC\
          lmaschine ist fertig, Geschirr rausnehmen!\"\n            ] | random }}"
        title: "\U0001F37D\uFE0F Geschirr ist sauber"
      service: notify.mobile_app_iphone_von_florian
alias: "K\xFCche Steckdosen Power Management"
description: ''
id: '1711970540815'
mode: single
trigger:
- entity_id:
  - sensor.steckdose_waschmaschine_energy_power
  for:
    hours: 0
    minutes: 2
    seconds: 0
  from: null
  id: washingMachineOffAfterTime
  platform: state
  to: '0'
- entity_id:
  - sensor.steckdose_spuhlmaschine_energy_power
  for:
    hours: 0
    minutes: 2
    seconds: 0
  from: null
  id: dishWasherOffAfterTime
  platform: state
  to: '0'
