actions:
- choose:
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: kochenStart
      - condition: trigger
        id: kochenDetected
      - condition: trigger
        id: kucheOccupied
    sequence:
    - action: light.turn_on
      data:
        brightness_pct: 90
        color_temp_kelvin: 4000
        transition: 2
      target:
        entity_id: light.lightener_kuche
    - action: climate.set_fan_mode
      continue_on_error: true
      data:
        fan_mode: high
      target:
        entity_id: climate.luftreiniger_wohnzimmer
    - action: notify.alexa_media_echo_show_wohnzimmer
      data:
        data:
          type: tts
        message: "K\xFCchenbeleuchtung und Bel\xFCftung wurden f\xFCr das Kochen optimiert"
alias: "K\xFCche: Intelligente Kochassistenz"
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: "Automatische Beleuchtung und Ventilation beim Kochen basierend auf K\xFC\
  hlschrank-Nutzung"
id: '1739974700001'
mode: restart
triggers:
- entity_id: binary_sensor.aqara_contact_kuhlschrank_contact
  from: 'off'
  id: kochenStart
  to: 'on'
  trigger: state
- entity_id: binary_sensor.kochen
  from: 'off'
  id: kochenDetected
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.hlk_ld2410_7137_anwesenheit
  for:
    seconds: 30
  from: 'off'
  id: kucheOccupied
  to: 'on'
  trigger: state
