action:
- choose:
  - alias: Luftreiniger nach Zone
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - zoneLeavePure
      - condition: state
        entity_id: sensor.people_home
        for:
          hours: 0
          minutes: 5
          seconds: 0
        state: '0'
    sequence:
    - data:
        fan_mode: high
      service: climate.set_fan_mode
      target:
        entity_id:
        - climate.luftreiniger_schlafzimmer
        - climate.luftreiniger_wohnzimmer
    - delay:
        hours: 0
        milliseconds: 0
        minutes: 10
        seconds: 0
    - data:
        fan_mode: low
      service: climate.set_fan_mode
      target:
        entity_id:
        - climate.luftreiniger_schlafzimmer
        - climate.luftreiniger_wohnzimmer
  - conditions:
    - condition: trigger
      id:
      - timeEveningPure
    sequence:
    - data:
        fan_mode: high
      service: climate.set_fan_mode
      target:
        entity_id:
        - climate.luftreiniger_schlafzimmer
    - delay:
        hours: 0
        milliseconds: 0
        minutes: 10
        seconds: 0
    - data:
        fan_mode: low
      service: climate.set_fan_mode
      target:
        entity_id:
        - climate.luftreiniger_schlafzimmer
alias: Luftreiniger
condition: []
description: ''
id: '1700167188286'
mode: single
trigger:
- alias: Luftreiniger nach Zone Trigger
  entity_id: person.florian_wartner
  event: leave
  id: zoneLeavePure
  platform: zone
  zone: zone.home
- alias: Luftreiniger Schlafzimmer Abends
  at: '20:30:00'
  id: timeEveningPure
  platform: time
