action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - meetingOn
      - macbookCameraOn
    sequence:
    - parallel:
      - alias: AWTRIX Publish Wohnzimmer
        data:
          payload: '{   "icon":"55236",   "text": "c37", "hold": true }'
          topic: awtrix_wohnzimmer/notify
        service: mqtt.publish
      - alias: "AWTRIX Publish B\xFCro"
        data:
          payload: '{   "icon":"55236",   "text": "c37", "hold": true }'
          topic: awtrix_buro/notify
        service: mqtt.publish
      - data:
          rgb_color:
          - 240
          - 0
          - 0
        metadata: {}
        service: light.turn_on
        target:
          entity_id: light.wled_please_do_disturb
  - conditions:
    - condition: trigger
      id:
      - meetingOff
      - macbookCameraOff
    sequence:
    - data: {}
      metadata: {}
      service: script.awtrix_dismiss_notification
    - device_id: 20ae8ae709d52ecf41d7141305fcb2b1
      domain: light
      entity_id: bda91f0704e155ce5c10002606ca8909
      type: turn_off
alias: Meeting
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1697199027134'
mode: single
trigger:
- entity_id:
  - sensor.teams_status
  from: unknown
  id: meetingOn
  platform: state
  to: InACall
- entity_id:
  - sensor.teams_status
  from: InACall
  id: meetingOff
  platform: state
  to: Available
- entity_id:
  - binary_sensor.macbook_pro_von_florian_camera_in_use
  id: macbookCameraOn
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.macbook_pro_von_florian_camera_in_use
  id: macbookCameraOff
  platform: state
  to: 'off'
