action:
- if:
  - condition: state
    entity_id: switch.steckdose_bett
    state: 'off'
  - condition: state
    entity_id: switch.steckdose_tv_schlafzimmer
    state: 'off'
  then:
  - parallel:
    - device_id: cee4b3caf72c6c64e4cf9115e5ad0c40
      domain: switch
      entity_id: 82f42d86b638d5bf6c7b3f54ee19ac1a
      type: turn_on
    - device_id: 687585a826f140c103f447d4384f11a8
      domain: switch
      entity_id: 107487a20fd417d6c27308fc10f3df40
      type: turn_on
alias: 'Motion: Schlafzimmer Steckdosen An'
condition:
- after: '21:00:00'
  before: 00:00:00
  condition: time
  weekday:
  - mon
  - fri
  - sat
  - sun
  - tue
  - wed
  - thu
description: ''
id: '1713444406391'
mode: single
trigger:
- device_id: 7166fbfe0af7d53d4673741c96c3863d
  domain: binary_sensor
  entity_id: 94bfc27f3b165fc352e2cc04541190d1
  platform: device
  type: motion
