actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - presenceOn
    sequence:
    - action: light.turn_on
      data:
        brightness_pct: 20
      metadata: {}
      target:
        entity_id: light.tv_bank
  - conditions:
    - condition: trigger
      id:
      - presenceOff
    sequence:
    - action: light.turn_off
      data: {}
      metadata: {}
      target:
        entity_id: light.tv_bank
alias: Nachtlicht Wohnzimmer
conditions:
- condition: state
  entity_id: input_boolean.night_mode
  state: 'on'
description: ''
id: '1745357440159'
mode: single
triggers:
- entity_id:
  - binary_sensor.presence_wohnzimmer_allgemein
  from: 'off'
  id: presenceOn
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.presence_wohnzimmer_allgemein
  for:
    hours: 0
    minutes: 0
    seconds: 5
  from: 'on'
  id: presenceOff
  to: 'off'
  trigger: state
