actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - kucheOn
    sequence:
    - brightness_pct: 30
      device_id: 7e56df9d6385100a6089783f6de066d7
      domain: light
      entity_id: 36aeda22c66e308e67721d47b46bf669
      type: turn_on
  - conditions:
    - condition: trigger
      id:
      - kucheOff
    sequence:
    - device_id: 7e56df9d6385100a6089783f6de066d7
      domain: light
      entity_id: 36aeda22c66e308e67721d47b46bf669
      type: turn_off
alias: "Nachtlicht K\xFCche"
conditions:
- condition: and
  conditions:
  - after: sunset
    after_offset: '1'
    before: sunrise
    before_offset: '1'
    condition: sun
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1691151128778'
mode: single
triggers:
- entity_id:
  - binary_sensor.hlk_ld2410_7137_anwesenheit
  from: 'off'
  id: kucheOn
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.hlk_ld2410_7137_anwesenheit
  from: 'on'
  id: kucheOff
  to: 'off'
  trigger: state
