actions:
- if:
  - after: sunset
    after_offset: '1'
    before: sunrise
    before_offset: '1'
    condition: sun
  then:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - badezimmerOn
      sequence:
      - action: light.turn_on
        data:
          brightness_pct: 30
        target:
          entity_id: light.decke_badezimmer
    - conditions:
      - condition: trigger
        id:
        - badezimmerOff
      sequence:
      - action: input_boolean.turn_off
        data: {}
        metadata: {}
        target:
          entity_id: input_boolean.klo_besetzt
      - if:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - after: sunset
              after_offset: '1'
              before: sunrise
              condition: sun
              enabled: true
            - condition: state
              enabled: false
              entity_id: input_boolean.guestmode
              state: 'off'
        then:
        - action: light.turn_off
          data: {}
          target:
            device_id: 6e5322a0a9b03a5d8858879bbead49bf
alias: Nachtlicht Badezimmer
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1691786451171'
mode: single
triggers:
- entity_id:
  - binary_sensor.mmwave_badezimmer
  for:
    hours: 0
    minutes: 0
    seconds: 2
  id: badezimmerOn
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.mmwave_badezimmer
  for:
    hours: 0
    minutes: 0
    seconds: 5
  id: badezimmerOff
  to: 'off'
  trigger: state
