action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - flurOn
    sequence:
    - brightness_pct: 30
      device_id: 1e56c698587f52128871b8ba472cfc47
      domain: light
      entity_id: 2c70b1a119850621e0cd9a85759fca40
      type: turn_on
  - conditions:
    - condition: trigger
      id:
      - flurOff
    sequence:
    - device_id: 1e56c698587f52128871b8ba472cfc47
      domain: light
      entity_id: 2c70b1a119850621e0cd9a85759fca40
      type: turn_off
alias: Nachtlicht Flur
condition:
- condition: and
  conditions:
  - after: sunset
    after_offset: '1'
    before: sunrise
    before_offset: '1'
    condition: sun
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: 20%
id: '1691358813636'
mode: single
trigger:
- entity_id:
  - binary_sensor.hlk_flur_belegung
  id: flurOn
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.hlk_flur_belegung
  from: 'on'
  id: flurOff
  platform: state
  to: 'off'
