action:
- data:
    message: "Home Assistant hat ein neues Ger\xE4t gefunden:             {{trigger.event.data.entity_id}}"
    title: "Neues Ger\xE4t gefunden"
  service: notify.home_ai
alias: "Neues Ger\xE4t gefunden (Notification)"
condition:
- condition: state
  entity_id: input_boolean.nicht_storen
  state: 'off'
description: ''
id: '1712905210678'
mode: single
trigger:
- event_type: device_tracker_new_device
  platform: event
