action:
- data: {}
  metadata: {}
  service: lock.open
  target:
    device_id: bb8a84cf268277f3d38063aee6ce698e
alias: "NFC Tag Wohnungst\xFCr ist gescannt"
condition: []
description: ''
id: '1718794967135'
mode: single
trigger:
- platform: tag
  tag_id: 80174732-d4b2-4c77-9e71-a05ff997192a
