actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - sunOff
    sequence:
    - action: input_boolean.turn_on
      data: {}
      metadata: {}
      target:
        entity_id: input_boolean.night_mode
  - conditions:
    - condition: trigger
      id:
      - sunOn
    sequence:
    - action: input_boolean.turn_off
      data: {}
      metadata: {}
      target:
        entity_id: input_boolean.night_mode
alias: Nightmode Toggle
conditions: []
description: ''
id: '1745356989733'
mode: single
triggers:
- event: sunset
  id: sunOff
  offset: '1'
  trigger: sun
- event: sunrise
  id: sunOn
  offset: 0
  trigger: sun
