actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - iphoneBatteryLowOn
    sequence:
    - action: switch.turn_on
      data: {}
      metadata: {}
      target:
        entity_id: switch.nuki_haustur_continuous_mode
  - conditions:
    - condition: trigger
      id:
      - iphoneBatteryLowOff
    sequence:
    - action: switch.turn_off
      data: {}
      metadata: {}
      target:
        entity_id: switch.nuki_haustur_continuous_mode
alias: Nuki Auto-Unlock iPhone Battery Low
conditions: []
description: ''
id: '1747658887532'
mode: single
triggers:
- entity_id:
  - binary_sensor.iphone_von_florian_battery_plus_low
  for:
    hours: 0
    minutes: 5
    seconds: 0
  from: 'off'
  id: iphoneBatteryLowOn
  to: 'on'
  trigger: state
- entity_id:
  - sensor.iphone_von_florian_battery_plus
  from: 'on'
  id: iphoneBatteryLowOff
  to: 'off'
  trigger: state
