action:
- data: {}
  service: homeassistant.update_entity
  target:
    entity_id:
    - binary_sensor.openuv_schutzfenster
    - sensor.openuv_aktueller_uv_index
    - sensor.openuv_aktueller_uv_wert
alias: 'OpenUV: Reload'
condition:
- condition: and
  conditions:
  - after: sunrise
    before: sunset
    condition: sun
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1716151253982'
mode: single
trigger:
- hours: /12
  platform: time_pattern
