action:
- data: {}
  service: person.reload
alias: 'Person: Reload'
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1713949268424'
mode: single
trigger:
- minutes: /2
  platform: time_pattern
