actions:
- action: light.turn_on
  data:
    flash: short
    rgb_color:
    - 97
    - 0
    - 133
  target:
    entity_id: light.tv
alias: PM25 Test Wohnzimmer
conditions:
- condition: state
  entity_id: light.tv
  state: 'on'
description: ''
id: '1728149871505'
mode: single
triggers:
- above: 25
  device_id: cc11e1fb1d90ed5a4cde9185cd2f1057
  domain: sensor
  entity_id: c18b4cef1a9167966f680cfaa3f4c50a
  metadata:
    secondary: false
  trigger: device
  type: pm25
