action:
- data:
    agent_id: conversation.chatgpt_butler
    language: german
    text: '{% set original_message = trigger.event.data.service_data.message %} {{
      original_message }}

      '
  metadata: {}
  response_variable: generated_response
  service: conversation.process
- data:
    message: '{{ states(''input_text.processed_message'') }}'
    title: '{{ trigger.event.data.service_data.title }}'
  metadata: {}
  service: notify.all_devices
alias: Process and Notify
condition: []
description: ''
id: '1718614598599'
mode: single
trigger:
- event_data:
    domain: notify
    service: home_ai
  event_type: call_service
  platform: event
