actions:
- action: conversation.process
  data:
    agent_id: conversation.chatgpt_assist
    language: german
    text: 'Briefly tell me that my {{ trigger.event.data.service_data.message }}.
      Always make sure that the message fits into 2 sentences.

      '
  metadata: {}
  response_variable: generated_response
- else:
  - action: notify.florian_notify
    data:
      message: '{{ generated_response.response.speech.plain.speech }}'
      title: '{{ trigger.event.data.service_data.title }}'
    metadata: {}
  if:
  - condition: template
    value_template: '{{ trigger.event.data.service_data.data.actions != null }}'
  then:
  - action: notify.florian_notify
    data:
      data:
        actions: '{{ trigger.event.data.service_data.data.actions }}'
      message: '{{ generated_response.response.speech.plain.speech }}'
      title: '{{ trigger.event.data.service_data.title }}'
    metadata: {}
alias: Process and Notify
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1718614598599'
mode: single
triggers:
- event_data:
    domain: notify
    service: home_ai
  event_type: call_service
  trigger: event
