actions:
- action: notify.persistent_notification
  data:
    message: 'High network transmit detected on Proxmox VM veth115i0. Current rate:
      {{ states(''sensor.glances_proxmox_pve_01_veth115i0_tx'') }} Mbit/s'
    title: Proxmox Network Alert
alias: Proxmox Network TX High Usage Alert
conditions: []
description: ''
id: '1745139592246'
mode: single
triggers:
- above: 10
  entity_id: sensor.glances_proxmox_pve_01_veth115i0_tx
  trigger: numeric_state
