action:
- data: {}
  metadata: {}
  service: button.press
  target:
    entity_id: button.unifi_express_restart
- data: {}
  service: hassio.host_shutdown
- delay:
    hours: 0
    milliseconds: 0
    minutes: 20
    seconds: 0
- data: {}
  service: homeassistant.reload_all
alias: Restart Nightly
condition: []
description: ''
id: '1719501882967'
mode: single
trigger:
- at: 04:00:00
  platform: time
