actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - coverCloseSchlafzimmer
    sequence:
    - action: cover.close_cover
      data: {}
      metadata: {}
      target:
        entity_id: cover.rollos_schlafzimmer
  - conditions:
    - condition: trigger
      id:
      - coverOpenSchlafzimmer
    sequence:
    - action: cover.open_cover
      data: {}
      metadata: {}
      target:
        entity_id: cover.rollos_schlafzimmer
alias: Rollos Schlafzimmer
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - condition: state
    entity_id: input_boolean.manuell
    state: 'off'
  - condition: state
    entity_id: input_boolean.rollos_schlafzimmer
    state: 'off'
  - condition: time
    weekday:
    - fri
    - thu
    - wed
    - tue
    - mon
description: ''
id: '1729247777105'
mode: single
triggers:
- at: '21:00:00'
  id: coverCloseSchlafzimmer
  trigger: time
- at: 08:30:00
  id: coverOpenSchlafzimmer
  trigger: time
