action:
- data: {}
  service: cover.open_cover
  target:
    entity_id:
    - cover.ikea_rollo_balkontur
    - cover.rollos_schlafzimmer
    - cover.rollos_wohnzimmer_fensterbank
alias: Rollos hoch wenn jemand nach Hause kommt
condition: []
description: ''
id: '1690714818053'
mode: single
trigger:
- entity_id:
  - sensor.people_home
  from: '0'
  platform: state
  to: '1'
