action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - coverKucheClose
    sequence:
    - data: {}
      service: cover.close_cover
      target:
        entity_id: cover.aqara_rollo_kuche
  - conditions:
    - condition: trigger
      id:
      - coverKucheOpen
    sequence:
    - data: {}
      service: cover.open_cover
      target:
        entity_id: cover.aqara_rollo_kuche
alias: "Rollo K\xFCche"
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1693489965780'
mode: single
trigger:
- event: sunset
  id: coverKucheClose
  offset: '1'
  platform: sun
- event: sunrise
  id: coverKucheOpen
  offset: '1'
  platform: sun
