actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - wohnzimmerRollosOn
    sequence:
    - action: cover.close_cover
      data: {}
      target:
        entity_id:
        - cover.ikea_rollo_links_wohnzimmer
        - cover.ikea_rollo_rechts_wohnzimmer
  - conditions:
    - condition: trigger
      id:
      - wohnzimmerRollosOff
    sequence:
    - action: cover.open_cover
      data: {}
      target:
        entity_id:
        - cover.ikea_rollo_links_wohnzimmer
        - cover.ikea_rollo_rechts_wohnzimmer
  - conditions:
    - condition: trigger
      id:
      - kucheRollosOn
    sequence: []
alias: "Rollos schlie\xDFen wenn zu hell"
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.zu_warm
    state: 'off'
  - condition: state
    entity_id: input_boolean.guestmode
    state: 'off'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - condition: state
    entity_id: input_boolean.rollos_wohnzimmer
    state: 'off'
description: ''
id: '1691320563612'
mode: single
triggers:
- above: 10000
  device_id: cc409c26cddb1137902b367f0bbcc342
  domain: sensor
  entity_id: fdf41f9caeca9372e6285dca0cc7d60f
  id: wohnzimmerRollosOn
  trigger: device
  type: illuminance
- below: 500
  device_id: cc409c26cddb1137902b367f0bbcc342
  domain: sensor
  entity_id: fdf41f9caeca9372e6285dca0cc7d60f
  id: wohnzimmerRollosOff
  trigger: device
  type: illuminance
