actions:
- choose:
  - conditions:
    - condition: trigger
      id: wohnzimmerRollosOn
    - condition: or
      conditions:
      - condition: state
        entity_id: cover.ikea_rollo_links_wohnzimmer
        state: open
      - condition: state
        entity_id: cover.ikea_rollo_rechts_wohnzimmer
        state: open
    sequence:
    - action: notify.alexa_media_echo_show_wohnzimmer
      data:
        message: Rollos werden aufgrund der Helligkeit geschlossen
    - action: cover.close_cover
      target:
        entity_id:
        - cover.ikea_rollo_links_wohnzimmer
        - cover.ikea_rollo_rechts_wohnzimmer
  - conditions:
    - condition: trigger
      id: wohnzimmerRollosOff
    - condition: and
      conditions:
      - condition: state
        entity_id: cover.ikea_rollo_links_wohnzimmer
        state: closed
      - condition: state
        entity_id: cover.ikea_rollo_rechts_wohnzimmer
        state: closed
    sequence:
    - action: cover.open_cover
      target:
        entity_id:
        - cover.ikea_rollo_links_wohnzimmer
        - cover.ikea_rollo_rechts_wohnzimmer
alias: "Rollos schlie\xDFen wenn zu hell"
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.zu_warm
    state: 'off'
  - condition: state
    entity_id: input_boolean.guestmode
    state: 'off'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - condition: state
    entity_id: input_boolean.rollos_wohnzimmer
    state: 'off'
  - after: 06:00:00
    before: '22:00:00'
    condition: time
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
description: "Intelligente Rollosteuerung basierend auf Lichst\xE4rke mit Zeitverz\xF6\
  gerung und mehreren Sicherheitsbedingungen"
id: '1691320563612'
mode: single
triggers:
- above: 15000
  entity_id: sensor.awtrix_ed6030_illuminance
  for:
    minutes: 10
  id: wohnzimmerRollosOn
  trigger: numeric_state
- below: 1000
  entity_id: sensor.awtrix_ed6030_illuminance
  for:
    minutes: 15
  id: wohnzimmerRollosOff
  trigger: numeric_state
