actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - wohnzimmerHellAn
    sequence:
    - action: cover.close_cover
      data: {}
      metadata: {}
      target:
        entity_id: cover.rollos_wohnzimmer_fensterbank
  - conditions:
    - condition: trigger
      id:
      - wohnzimmerHellAus
    sequence:
    - action: cover.open_cover
      data: {}
      metadata: {}
      target:
        entity_id: cover.rollos_wohnzimmer_fensterbank
alias: Rollos Wohnzimmer
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - condition: state
    entity_id: input_boolean.manuell
    state: 'off'
  - condition: state
    entity_id: input_boolean.rollos_wohnzimmer
    state: 'on'
  - above: 0
    condition: numeric_state
    entity_id: sensor.people_home
description: ''
id: '1740091713939'
mode: single
triggers:
- above: 1000
  entity_id:
  - sensor.mi_light_sensor_wohnzimmer_illuminance
  for:
    hours: 0
    minutes: 3
    seconds: 0
  id: wohnzimmerHellAn
  trigger: numeric_state
- below: 300
  entity_id:
  - sensor.mi_light_sensor_wohnzimmer_illuminance
  for:
    hours: 0
    minutes: 5
    seconds: 0
  id: wohnzimmerHellAus
  trigger: numeric_state
