actions:
- action: readme.generate
  data: {}
- action: shell_command.run_chores
  data: {}
alias: Run Chores
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: Reduziert auf alle 30 Minuten zur Lastreduktion
id: '1713209575955'
mode: single
triggers:
- minutes: /30
  trigger: time_pattern
