action:
- data: {}
  service: readme.generate
- data: {}
  response_variable: backup_response
  service: shell_command.run_chores
alias: Run Chores
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1713209575955'
mode: single
trigger:
- minutes: /10
  platform: time_pattern
