action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - nukiAutoUnlockOn
    sequence:
    - data: {}
      enabled: true
      metadata: {}
      service: switch.turn_on
      target:
        entity_id:
        - switch.nuki_haustur_continuous_mode
    - data:
        message: "{{ [ \"Bis gleich!\", \"Bis gleich dann!\", \"Sehen uns gleich!\"\
          , \"Gleich sehen wir uns!\", \"Bis gleich, in ein paar Minuten!\", \"Bis\
          \ gleich, freue mich!\", \"Bin bald bei dir, bis gleich!\", \"Wir sehen\
          \ uns gleich wieder!\", \"Nur noch kurz, bis gleich!\", \"Bis gleich, nicht\
          \ weglaufen!\", \"Bis gleich, halte die Stellung!\", \"Wir treffen uns gleich,\
          \ bis dahin!\", \"Bis gleich, mach's gut!\", \"Bis gleich, ich beeile mich!\"\
          , \"Gleich bin ich zur\xFCck, bis gleich!\", \"Sehen uns gleich, halt die\
          \ Ohren steif!\", \"Bis gleich, lass dich nicht unterkriegen!\", \"Bis gleich,\
          \ das wird super!\", \"Gleich sind wir wieder zusammen, bis gleich!\", \"\
          Bis gleich, ich z\xE4hle die Minuten!\", \"Bis gleich, halt alles bereit!\"\
          , \"Bis gleich, ich freu mich schon!\" ] | random }}"
      metadata: {}
      service: notify.alexa_media_echo_flur
  - conditions:
    - condition: trigger
      id:
      - nukiAutoUnlockOff
    sequence:
    - data: {}
      service: switch.turn_off
      target:
        entity_id:
        - switch.nuki_haustur_continuous_mode
    - data:
        message: Auto-Unlock wurde abgeschaltet
      service: notify.alexa_media_echo_flur
  - conditions:
    - condition: trigger
      id:
      - nukiOn
    sequence:
    - device_id: 0bd3a8ef3dbdde3611e8f7f2b0d33f35
      domain: switch
      entity_id: 55c2f5c9869bcfbeac0ed4d2dfbc4567
      type: turn_on
  - conditions:
    - condition: trigger
      id:
      - nukiOff
    sequence:
    - device_id: 0bd3a8ef3dbdde3611e8f7f2b0d33f35
      domain: switch
      entity_id: 55c2f5c9869bcfbeac0ed4d2dfbc4567
      type: turn_off
alias: Schalter Flur Nuki
condition: []
description: ''
id: '1713885934064'
mode: single
trigger:
- device_id: 0bd3a8ef3dbdde3611e8f7f2b0d33f35
  domain: switch
  entity_id: 55c2f5c9869bcfbeac0ed4d2dfbc4567
  id: nukiAutoUnlockOn
  platform: device
  type: turned_on
- device_id: 0bd3a8ef3dbdde3611e8f7f2b0d33f35
  domain: switch
  entity_id: 55c2f5c9869bcfbeac0ed4d2dfbc4567
  id: nukiAutoUnlockOff
  platform: device
  type: turned_off
- entity_id:
  - switch.nuki_haustur_continuous_mode
  from: 'off'
  id: nukiOn
  platform: state
  to: 'on'
- entity_id:
  - switch.nuki_haustur_continuous_mode
  from: 'on'
  id: nukiOff
  platform: state
  to: 'off'
