action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - schalterFlurAn
    sequence:
    - device_id: 4b04528f90d6106276926f279e2d4cb6
      domain: light
      entity_id: 95eab0e0f096de60d69cc6204752c455
      type: turn_on
  - conditions:
    - condition: trigger
      id:
      - schalterFlurAus
    sequence:
    - device_id: 4b04528f90d6106276926f279e2d4cb6
      domain: light
      entity_id: 95eab0e0f096de60d69cc6204752c455
      type: turn_off
  - conditions:
    - condition: trigger
      id:
      - deckeFlurAus
    sequence:
    - data: {}
      service: switch.turn_off
      target:
        entity_id:
        - switch.flur_schalter_decke
  - conditions:
    - condition: trigger
      id:
      - deckeFlurAn
    sequence:
    - data: {}
      service: switch.turn_on
      target:
        entity_id:
        - switch.flur_schalter_decke
alias: Schalter Flur Deckenlicht
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1713448133488'
mode: single
trigger:
- device_id: 0bd3a8ef3dbdde3611e8f7f2b0d33f35
  domain: switch
  entity_id: e121bb409464ba167ad31f9375490156
  id: schalterFlurAn
  platform: device
  type: turned_on
- device_id: 0bd3a8ef3dbdde3611e8f7f2b0d33f35
  domain: switch
  entity_id: e121bb409464ba167ad31f9375490156
  id: schalterFlurAus
  platform: device
  type: turned_off
- device_id: 4b04528f90d6106276926f279e2d4cb6
  domain: light
  entity_id: 95eab0e0f096de60d69cc6204752c455
  id: deckeFlurAus
  platform: device
  type: turned_off
- device_id: 4b04528f90d6106276926f279e2d4cb6
  domain: light
  entity_id: 95eab0e0f096de60d69cc6204752c455
  id: deckeFlurAn
  platform: device
  type: turned_on
