actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - timeOn
    sequence:
    - action: script.activate_alexa_actionable_notification
      data:
        alexa_device: media_player.echo_show_wohnzimmer
        event_id: alexa_actionable_notification_bettzeit
        suppress_confirmation: true
        text: Es ist 22:30... Willst du nicht langsam schlafen gehen?
  - conditions:
    - condition: trigger
      id:
      - alexaResponse
    sequence:
    - action: script.schlafenszeit
      data: {}
      metadata: {}
alias: Schlafenszeit
conditions:
- above: 0
  condition: numeric_state
  entity_id: sensor.people_home
description: ''
id: '1731345953307'
mode: single
triggers:
- at: '22:30:00'
  id: timeOn
  trigger: time
- event_data:
    event_id: alexa_actionable_notification_bettzeit
    event_response_type: ResponseYes
  event_type: alexa_actionable_notification
  id: alexaResponse
  trigger: event
