actions:
- action: script.staubsauger_schlafzimmer_reinigen_reinigen
  data: {}
  metadata: {}
alias: Schlafzimmer Reinigen
conditions: []
description: ''
id: '1739969760920'
mode: single
triggers:
- command:
  - Reinige das Schlafzimmer
  - Schicke den Staubsauger ins Schlafzimmer
  - Schlafzimmer reinigen
  trigger: conversation
