action:
- data: {}
  service: script.1699263899938
alias: Speedtest
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: "Alle 30 Minuten (stabilit\xE4tsoptimiert)"
id: '1699291427370'
mode: single
trigger:
- minutes: /30
  platform: time_pattern
