actions:
- parallel:
  - device_id: cee4b3caf72c6c64e4cf9115e5ad0c40
    domain: switch
    entity_id: 82f42d86b638d5bf6c7b3f54ee19ac1a
    type: turn_off
  - device_id: 687585a826f140c103f447d4384f11a8
    domain: switch
    entity_id: 107487a20fd417d6c27308fc10f3df40
    type: turn_off
alias: Steckdosen Schlafzimmer Morgens Aus
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - condition: state
    entity_id: input_boolean.manuell
    state: 'off'
description: ''
id: '1713444564715'
mode: single
triggers:
- at: 08:00:00
  trigger: time
