action:
- data:
    apply_filter: true
    repack: true
  service: recorder.purge
alias: System - Database Repack (Weekly)
condition:
- condition: and
  conditions:
  - condition: time
    weekday:
    - sun
    - tue
    - thu
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: database_repack
mode: single
trigger:
- at: 02:00
  platform: time
