action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - waschmaschinenTabsCounterLow
    sequence:
    - data:
        item: Waschmaschinentabs
      metadata: {}
      service: todo.add_item
      target:
        entity_id:
        - todo.einkaufsliste
    - data:
        data:
          actions:
          - action: URI
            title: Zur Einkaufsliste
            uri: /todo?entity_id=todo.einkaufsliste
        message: Deine Waschmaschine hat bald keine Tabs mehr. Geh doch mal wieder
          welche einkaufen.
        title: "\U0001F6D2 Waschmaschinentabs sind fast leer "
      service: notify.home_ai
  - conditions:
    - condition: trigger
      id:
      - spuelmaschinenTabsCounterLow
    sequence:
    - data:
        item: "Sp\xFClmaschinentabs"
      metadata: {}
      service: todo.add_item
      target:
        entity_id:
        - todo.einkaufsliste
    - data:
        data:
          actions:
          - action: URI
            title: Zur Einkaufsliste
            uri: /todo?entity_id=todo.einkaufsliste
        message: "Deine Sp\xFClmaschine hat bald keine Tabs mehr. Geh doch mal wieder\
          \ welche einkaufen."
        title: "\U0001F6D2 Sp\xFClmaschinentabs sind fast leer "
      service: notify.home_ai
alias: Tabs bald leer
condition: []
description: ''
id: '1718551651013'
mode: single
trigger:
- below: 5
  entity_id:
  - input_number.waschmaschinentabs
  id: waschmaschinenTabsCounterLow
  platform: numeric_state
- below: 5
  entity_id:
  - input_number.spulmaschinentabs
  id: spuelmaschinenTabsCounterLow
  platform: numeric_state
