action:
- data:
    message: Jemand ruft dich an.
    title: Das Telefon klingelt
  service: notify.home_ai
alias: Telefon Zuhause
condition: []
description: ''
id: '1710416045878'
mode: single
trigger:
- entity_id:
  - sensor.fritz_box_6591_cable_kdg_anrufmonitor_telefonbuch
  platform: state
  to: ringing
