action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - eveningOn
    sequence:
    - data: {}
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.abend
  - conditions:
    - condition: trigger
      id:
      - eveningOff
    sequence:
    - data: {}
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.abend
alias: Toggle Abend / Morgen
condition:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1716668889277'
mode: single
trigger:
- at: '20:00:00'
  id: eveningOn
  platform: time
- at: 06:00:00
  id: eveningOff
  platform: time
