actions:
- continue_on_timeout: false
  wait_template: "{% set fenster = [\n            'binary_sensor.aqara_contact_badezimmer_contact',\n\
    \            'binary_sensor.aqara_contact_balkontur_contact',\n            'binary_sensor.aqara_contact_kinderzimmer_contact',\n\
    \            'binary_sensor.aqara_contact_wohnungstur_contact',\n            'binary_sensor.aqara_contact_wohnzimmer_contact',\n\
    \            'binary_sensor.aqara_contact_schlafzimmer_contact',\n           \
    \ ] %}\n          {% if fenster | select('is_state', 'on') | list | count > 0\
    \ %}\n            true\n          {% else %}\n            false\n          {%\
    \ endif %}"
- if:
  - condition: state
    entity_id: input_boolean.nicht_storen
    state: 'off'
  then:
  - action: notify.home_ai
    data:
      message: "Es sieht so aus, als w\xE4ren noch eine oder mehrere T\xFCren offen.\
        \ Pr\xFCfe doch mal nach, welche das sein k\xF6nnten und schlie\xDFe sie gegebenenfalls\
        \ bevor du gehst."
      title: "Es sind noch T\xFCren offen"
    metadata: {}
- action: notify.alexa_media_echo_flur
  data:
    message: "Es sieht so aus, als w\xE4ren noch eine oder mehrere T\xFCren offen.\
      \ Pr\xFCfe doch mal nach, welche das sein k\xF6nnten und schlie\xDFe sie gegebenenfalls\
      \ bevor du gehst."
  enabled: false
  metadata: {}
alias: "T\xFCren Offen Check"
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.urlaubsmodus
    state: 'on'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1713181284693'
mode: single
triggers:
- device_id: 67bc89621a1ceb0aced67ad07618a34b
  domain: hue
  subtype: 1
  trigger: device
  type: short_release
  unique_id: f88e3a46-3b79-423c-868f-7ad7944c62bc
