actions:
- choose:
  - alias: Notification Florian
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - zoneHomeOn
        - nukiRingOn
    sequence:
    - action: notify.florian_notify
      data:
        data:
          actions:
          - action: UNLOCK_HOUSE
            icon: sfsymbols:lock.open.fill
            title: "Haust\xFCr \xF6ffnen"
          - action: UNLOCK_APARTMENT
            icon: sfsymbols:lock.open.fill
            title: "Wohnungst\xFCr \xF6ffnen"
        message: "M\xF6chtest du die T\xFCr \xF6ffnen?"
        title: "\U0001F510 T\xFCren \xF6ffnen"
  - alias: Notification Steffi
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - nukiRingOn
        - zoneHomeOnSteffi
    sequence:
    - action: notify.florian_notify
      data:
        data:
          actions:
          - action: UNLOCK_HOUSE
            icon: sfsymbols:lock.open.fill
            title: "Haust\xFCr \xF6ffnen"
          - action: UNLOCK_APARTMENT
            icon: sfsymbols:lock.open.fill
            title: "Wohnungst\xFCr \xF6ffnen"
        message: "M\xF6chtest du die T\xFCr \xF6ffnen?"
        title: "\U0001F510 T\xFCren \xF6ffnen"
      enabled: true
  - alias: "Haust\xFCr \xD6ffnen"
    conditions:
    - condition: trigger
      id:
      - unlockHouse
    sequence:
    - action: lock.open
      data: {}
      target:
        entity_id: lock.nuki_haustur_lock
  - alias: "Wohnungst\xFCr \xD6ffnen"
    conditions:
    - condition: trigger
      id:
      - unlockApartment
    sequence:
    - action: lock.open
      data: {}
      target:
        entity_id: lock.nuki_wohnungstur_lock
alias: "T\xFCren"
conditions:
- condition: state
  entity_id: input_boolean.wartung
  state: 'off'
description: ''
id: '1702827571661'
mode: single
triggers:
- entity_id: person.florian_wartner
  event: enter
  id: zoneHomeOn
  trigger: zone
  zone: zone.home
- entity_id:
  - binary_sensor.nuki_haustur_ring_action
  id: nukiRingOn
  to: 'on'
  trigger: state
- event_data:
    action: UNLOCK_HOUSE
  event_type: mobile_app_notification_action
  id: unlockHouse
  trigger: event
- event_data:
    action: UNLOCK_APARTMENT
  event_type: mobile_app_notification_action
  id: unlockApartment
  trigger: event
- entity_id: person.steffi
  event: enter
  id: zoneHomeOnSteffi
  trigger: zone
  zone: zone.home
