action:
- choose:
  - conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - ringOn
      - below: 1
        condition: numeric_state
        entity_id: sensor.people_home
    sequence:
    - data:
        message: "Scheinbar hat jemand an der T\xFCr geklingelt."
        title: "Jemand hat an der T\xFCr geklingelt.."
      service: notify.mobile_app_iphone_von_florian
  - conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - ringOn
      - above: 0
        condition: numeric_state
        entity_id: sensor.people_home
    sequence:
    - parallel:
      - repeat:
          count: '3'
          sequence:
          - data:
              color_name: gold
            service: light.turn_on
            target:
              device_id: 81a05f4ea38ce123a73f5f66b8e0e3c1
          - delay:
              hours: 0
              milliseconds: 0
              minutes: 0
              seconds: 1
          - data: {}
            service: light.turn_off
            target:
              device_id: 81a05f4ea38ce123a73f5f66b8e0e3c1
          - delay:
              hours: 0
              milliseconds: 0
              minutes: 0
              seconds: 1
      - data:
          message: "Jemand hat an der T\xFCr geklingelt"
        enabled: false
        service: notify.alexa_media_echo_show_wohnzimmer
      - data: {}
        metadata: {}
        service: script.awtrix_doorbell
  - conditions:
    - condition: trigger
      id:
      - ringOn
    sequence:
    - data:
        message: "Jemand hat an der T\xFCr geklingelt"
        title: "\U0001F514 Klingeling!"
      metadata: {}
      service: notify.mobile_app_macbook_pro_von_florian
alias: "T\xFCrklingel"
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.nicht_storen
    state: 'off'
  - above: 0
    condition: numeric_state
    entity_id: sensor.people_home
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1692134639284'
mode: single
trigger:
- entity_id:
  - binary_sensor.nuki_haustur_ring_action
  id: ringOn
  platform: state
  to: 'on'
