actions:
- parallel:
  - action: notify.mobile_app_mac_mini_von_florian
    data:
      message: "Jemand scheint an der T\xFCr zu sein\u2026"
      title: Es hat geklingelt!
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: trigger
          id:
          - ringOn
        - below: 1
          condition: numeric_state
          entity_id: sensor.people_home
      sequence:
      - action: notify.mobile_app_iphone_von_florian
        data:
          message: "Scheinbar hat jemand an der T\xFCr geklingelt."
          title: "Jemand hat an der T\xFCr geklingelt.."
    - conditions:
      - condition: and
        conditions:
        - condition: trigger
          id:
          - ringOn
        - above: 0
          condition: numeric_state
          entity_id: sensor.people_home
      sequence:
      - parallel:
        - repeat:
            count: '3'
            sequence:
            - action: light.turn_on
              data:
                color_name: gold
              target:
                device_id: 81a05f4ea38ce123a73f5f66b8e0e3c1
            - delay:
                hours: 0
                milliseconds: 0
                minutes: 0
                seconds: 1
            - action: light.turn_off
              data: {}
              target:
                device_id: 81a05f4ea38ce123a73f5f66b8e0e3c1
            - delay:
                hours: 0
                milliseconds: 0
                minutes: 0
                seconds: 1
        - action: notify.alexa_media_echo_show_wohnzimmer
          data:
            message: "Jemand hat an der T\xFCr geklingelt"
          enabled: false
        - action: script.awtrix_doorbell
          data: {}
          metadata: {}
    - conditions:
      - condition: trigger
        id:
        - ringOn
      sequence:
      - action: notify.mobile_app_macbook_pro_von_florian
        data:
          message: "Jemand hat an der T\xFCr geklingelt"
          title: "\U0001F514 Klingeling!"
        metadata: {}
alias: "T\xFCrklingel"
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.nicht_storen
    state: 'off'
  - above: 0
    condition: numeric_state
    entity_id: sensor.people_home
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1692134639284'
mode: single
triggers:
- entity_id:
  - binary_sensor.nuki_haustur_ring_action
  id: ringOn
  to: 'on'
  trigger: state
