actions:
- else:
  - action: cover.close_cover
    data: {}
    metadata: {}
    target:
      entity_id: cover.rollos_wohnzimmer_fensterbank
  if:
  - condition: state
    entity_id: cover.rollos_wohnzimmer_fensterbank
    state: closed
  then:
  - action: cover.open_cover
    data: {}
    metadata: {}
    target:
      entity_id: cover.rollos_wohnzimmer_fensterbank
alias: Universal Remote Test
conditions: []
description: ''
id: '1739973037216'
mode: single
triggers:
- entity_id:
  - event.universal_remote_rollos
  trigger: state
