actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - universalRemoteRollos
    sequence:
    - else:
      - action: cover.close_cover
        data: {}
        metadata: {}
        target:
          entity_id: cover.rollos_wohnzimmer_fensterbank
      if:
      - condition: state
        entity_id: cover.rollos_wohnzimmer_fensterbank
        state: closed
      then:
      - action: cover.open_cover
        data: {}
        metadata: {}
        target:
          entity_id: cover.rollos_wohnzimmer_fensterbank
  - conditions:
    - condition: trigger
      id:
      - universalRemoteFernsehen
    sequence:
    - action: input_boolean.toggle
      data: {}
      metadata: {}
      target:
        entity_id: input_boolean.fernsehen_szene
    - action: remote.turn_on
      data: {}
      metadata: {}
      target:
        device_id: 67feb204d2fca3cfd31e143defa33fe5
    - else:
      - action: scene.turn_on
        data:
          transition: 5
        metadata: {}
        target:
          entity_id: scene.wohnzimmer_aus
      - action: remote.turn_off
        data: {}
        metadata: {}
        target:
          device_id: 67feb204d2fca3cfd31e143defa33fe5
      if:
      - condition: state
        entity_id: input_boolean.fernsehen_szene
        state: 'on'
      then:
      - action: notify.alexa_media_echo_show_wohnzimmer
        data:
          message: "Ich richte das Wohnzimmer f\xFCr gem\xFCtliches Fernsehen her."
        metadata: {}
      - action: scene.turn_on
        data:
          transition: 5
        metadata: {}
        target:
          entity_id: scene.fernsehen
  - conditions:
    - condition: trigger
      id:
      - universalRemoteZocken
    sequence:
    - action: input_boolean.toggle
      data: {}
      metadata: {}
      target:
        entity_id: input_boolean.zocken_szene
    - else:
      - action: scene.turn_on
        data:
          transition: 5
        metadata: {}
        target:
          entity_id: scene.wohnzimmer_aus
      - device_id: cbed685d51c54392c35961266c9566f1
        domain: switch
        entity_id: f564dc00c2557356ac0d4f531b608d1c
        type: turn_off
      if:
      - condition: state
        entity_id: input_boolean.zocken_szene
        state: 'on'
      then:
      - action: notify.alexa_media_echo_show_wohnzimmer
        data:
          message: "Ich richte das Wohnzimmer f\xFCr gem\xFCtliches Zocken her."
        metadata: {}
      - action: scene.turn_on
        data: {}
        metadata: {}
        target:
          entity_id: scene.zocken
  - conditions:
    - condition: trigger
      id:
      - universalRemoteWohnzimmerAus
    sequence:
    - action: scene.turn_on
      data:
        transition: 5
      metadata: {}
      target:
        entity_id: scene.wohnzimmer_aus
    - action: cover.open_cover
      data: {}
      metadata: {}
      target:
        area_id: wohnzimmer
        device_id:
        - 2c6903e160b7b9dfaf222a7360bc0015
        - 5556afe8383ee4a45f5b74e6cc1d57ee
    - device_id: cbed685d51c54392c35961266c9566f1
      domain: switch
      entity_id: f564dc00c2557356ac0d4f531b608d1c
      type: turn_off
    - action: remote.turn_off
      data: {}
      metadata: {}
      target:
        device_id: 67feb204d2fca3cfd31e143defa33fe5
alias: Universal Remote Test
conditions: []
description: ''
id: '1739973037216'
mode: single
triggers:
- entity_id:
  - event.universal_remote_rollos
  id: universalRemoteRollos
  trigger: state
- entity_id:
  - event.universal_remote_fernsehen
  id: universalRemoteFernsehen
  trigger: state
- entity_id:
  - event.universal_remote_zocken
  id: universalRemoteZocken
  trigger: state
- entity_id:
  - event.universal_remote_wohnzimmer_aus
  id: universalRemoteWohnzimmerAus
  trigger: state
