actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - universalRemoteLeiser
    sequence:
    - action: media_player.volume_down
      data: {}
      metadata: {}
      target:
        device_id: 9d14dca47a5773d55c5f7f9d16c58476
alias: Universal Remote Volume
conditions: []
description: ''
id: '1733504268109'
mode: single
triggers:
- device_id: 688bd266db656755141bcb1a539bd837
  domain: button
  entity_id: 7adbb803bb6232733d9ab1a63f354814
  id: universalRemoteLeiser
  trigger: device
  type: pressed
