action:
- data: {}
  service: homeassistant.update_entity
  target:
    entity_id:
    - sensor.openuv_aktueller_uv_index
    - binary_sensor.openuv_schutzfenster
alias: Update OpenUV every 59 minutes during the daytime
condition:
- after: sunrise
  before: sunset
  condition: sun
description: ''
id: 90a76832-88a6-4da3-94f6-975154c297ff
trigger:
- minutes: 59
  platform: time_pattern
