action:
- choose:
  - conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - fanOn
    sequence:
    - data:
        percentage: 60
      service: fan.turn_on
      target:
        entity_id: fan.ventilator_wohnzimmer
  - conditions:
    - condition: trigger
      id:
      - fanOff
    sequence:
    - data: {}
      service: fan.turn_off
      target:
        entity_id: fan.ventilator_wohnzimmer
alias: Ventilator
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.ventilator
    state: 'on'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
  - condition: template
    value_template: '{{ now().month in [6,7,8] }}'
description: "An: Wenn \xFCber 25 Grad im Sommer, Aus: Wenn unter 23 Grad"
id: '1686557247104'
mode: single
trigger:
- above: 25
  entity_id:
  - sensor.wohnzimmer_temperature
  id: fanOn
  platform: numeric_state
- below: 23
  entity_id:
  - sensor.wohnzimmer_temperature
  id: fanOff
  platform: numeric_state
