action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - anyoneHomeOff
    sequence:
    - data: {}
      service: light.turn_off
      target:
        entity_id: light.alle_lampen
    - data: {}
      service: switch.turn_off
      target:
        entity_id:
        - switch.alle_steckdosen
alias: Verlassen
condition: []
description: ''
id: '1692084370120'
mode: single
trigger:
- entity_id:
  - sensor.people_home
  id: anyoneHomeOff
  platform: state
  to: '0'
