actions:
- action: fully_kiosk.load_url
  data:
    url: https://ha.wartner.cloud/dashboard-nspanel/1
  target:
    device_id: 3738295208de8496912ccf373503aa6c
- device_id: bb8a84cf268277f3d38063aee6ce698e
  domain: lock
  entity_id: 7b91d36587ba4469f26de8a280995404
  type: unlock
- if:
  - condition: state
    entity_id: input_boolean.auto_wecker
    state: 'off'
  then:
  - action: input_boolean.turn_off
    data: {}
    metadata: {}
    target:
      entity_id: input_boolean.wecker_an_aus
alias: Wecker
conditions:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.wecker_an_aus
    state: 'on'
  - condition: state
    entity_id: input_boolean.nicht_storen
    state: 'off'
  - condition: state
    entity_id: input_boolean.wartung
    state: 'off'
description: ''
id: '1712525174898'
mode: single
triggers:
- at: input_datetime.wecker
  enabled: true
  trigger: time
