actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - wledTVOn
    sequence:
    - action: light.turn_on
      data:
        transition: 2
      metadata: {}
      target:
        entity_id: light.wled_stand
  - conditions:
    - condition: trigger
      id:
      - wledTVOff
    sequence:
    - action: light.turn_off
      data:
        transition: 2
      metadata: {}
      target:
        entity_id: light.wled_stand
  - conditions:
    - condition: trigger
      id:
      - checkPower
    sequence:
    - action: homeassistant.update_entity
      data:
        entity_id:
        - sensor.steckdose_tv_schlafzimmer_energy_power
alias: WLED TV SZ ON OFF
conditions: []
description: ''
id: '1748208734437'
mode: single
triggers:
- above: 20
  entity_id:
  - sensor.steckdose_tv_schlafzimmer_energy_power
  id: wledTVOn
  trigger: numeric_state
- below: 20
  entity_id:
  - sensor.steckdose_tv_schlafzimmer_energy_power
  id: wledTVOff
  trigger: numeric_state
- id: checkPower
  seconds: '2'
  trigger: time_pattern
