actions:
- action: vacuum.start
  data: {}
  metadata: {}
  target:
    entity_id: vacuum.roborock_s7_maxv
alias: Wohnung reinigen komplett
conditions:
- after: 08:00:00
  before: '20:00:00'
  condition: time
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
description: ''
id: '1745312911625'
mode: single
triggers:
- below: 1
  entity_id:
  - sensor.people_home
  for:
    hours: 0
    minutes: 10
    seconds: 0
  trigger: numeric_state
