actions:
- action: script.staubsauger_wohnzimmer_reinigen
  data: {}
  metadata: {}
alias: Wohnzimmer Reinigen
conditions: []
description: ''
id: '1739969686639'
mode: single
triggers:
- command:
  - Reinige das Wohnzimmer
  - Schicke den Staubsauger ins Wohnzimmer
  - Wohnzimmer reinigen
  trigger: conversation
