action:
- data: {}
  metadata: {}
  service: light.turn_on
  target:
    device_id:
    - 8d09b3d2460d7b46609a435e034c3a59
    - 916ac0645e12fe77d93d9731956888e4
    - 1e74380a353e5af91767df2483e266fe
    - 171cf6e6bd2c823a2a91c916b23b3e25
    - 3d2124b0362a0b5d69b4f905ec8a36c5
alias: Wohnzimmer Licht wenn zu dunkel
condition:
- condition: and
  conditions:
  - above: 1
    condition: numeric_state
    entity_id: sensor.people_home
  - condition: state
    entity_id: remote.appletv_wohnzimmer
    state: 'on'
  - after: sunset
    condition: sun
description: ''
id: '1719174034446'
mode: single
trigger:
- below: 30
  entity_id:
  - sensor.mi_light_sensor_wohnzimmer_illuminance_lux
  platform: numeric_state
