---
- platform: universal
    name: Alle Player
    children:
      - media_player.sonos_ray_wohnzimmer
      - media_player.homepod_wohnzimmer
      - media_player.echo_badezimmer
      - media_player.echo_schlafzimmer
      - media_player.echo_badezimmer
      - media_player.echo_buro
      - media_player.echo_kuche
      - media_player.echo_show_wohnzimmer