---
- platform: media_player_template
  media_players:
    current_player:
      friendly_name: Current Player
      device_class: speaker
      current_source_template: "{{ states('sensor.current_media_player') }}"
      album_art_template: "{{ states('sensor.current_media_player_image') }}"
      title_template: "{{ states('sensor.current_media_player_title') }}"
      artist_template: "{{ states('sensor.current_media_player_artist') }}"
      value_template: >
        {% set activePlayer = states('sensor.current_media_player') %}
        {% if is_state(activePlayer, "playing") -%}
          on
        {%- else -%}
          off
        {%- endif %}
      turn_on:
      turn_off:
