---
- platform: media_player_template
  media_players:
    current_player:
      friendly_name: Current Player
      current_source_template: "{{ states('sensor.current_media_player') }}"
      album_art_template: "{{ states('sensor.current_media_player_image') }}"
      title_template: "{{ states('sensor.current_media_player_title') }}"
      artist_template: "{{ states('sensor.current_media_player_artist') }}"
