---
namespace: hass
requires_auth: true
component_config_glob:
  sensor.*_hum:
    override_metric: humidity_percent
  sensor.*_temp:
    override_metric: temperature_c
  sensor.temperature*:
    override_metric: temperature_c
  sensor.*_bat:
    override_metric: battery_percent
filter:
  include_domains:
    - sensor
  exclude_entity_globs:
    - sensor.weather_*
