##########
# This Blueprint is created by Smart Home Junkie
# (c) copyright 2023 by Smart Home Junkie. You may not copy, reproduce, distribute, transmit, modify, create derivative works,
# or in any other way exploit any part of copyrighted material without the prior written permission from Smart Home Junkie
##########

blueprint:
  name: Awtrix Weather App
  description: Show Weather on the Ulanzi Clock
  domain: automation
  author: Smart Home Junkie
  input:
    awtrix_displays:
      name: Awtrix Displays
      description: Select the target Awtrix displays.
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true
    toggle_helper:
      name: Toggle Helper
      description: Select the Toggle Helper that will toggle the App on or off.
      selector:
        entity:
          domain: input_boolean
    my_sensor:
      name: Sensor
      description: Select your Weather Sensor.
      selector:
        entity:
          domain: weather
    show_text:
      name: Show Weather Text
      description: Should the weather condition be shown as text?
      selector:
        boolean:
      default: true
    language:
      name: Language
      description: Show the weather condition in this language
      selector:
        select:
          options:
            - label: "English"
              value: "en"
            - label: "Dutch"
              value: "nl"
            - label: "French"
              value: "fr"
            - label: "German"
              value: "de"
            - label: "Polish"
              value: "pl"
            - label: "Portuguese"
              value: "pt"
            - label: "Spanish"
              value: "es"
          mode: dropdown
      default: "en"
    show_temperature:
      name: Show temperature
      description: Should the temperature be shown?
      selector:
        boolean:
      default: true
    show_windspeed:
      name: Show Wind Speed
      description: Should the wind speed be shown?
      selector:
        boolean:
      default: true
    show_humidity:
      name: Show Humidity
      description: Should the humidity be shown?
      selector:
        boolean:
      default: true
    push_icon:
      name: Push Icon
      description: Icon behavior
      selector:
        select:
          options:
            - label: "Icon doesn't move"
              value: "0"
            - label: "Icon moves with text and will not appear again"
              value: "1"
            - label: "Icon moves with text but appears again when the text starts"
              value: "2"
          mode: dropdown
      default: "2"
    text_case:
      name: Text Case
      description: Select how you would like your text to display.
      selector:
        select:
          options:
            - label: "Use global setting"
              value: "0"
            - label: "Force Uppercase"
              value: "1"
            - label: "Show as you entered it"
              value: "2"
          mode: dropdown
      default: "0"
    background_color:
      name: Background Color
      description: Select the Background color
      selector:
        color_rgb:
      default: [0, 0, 0]
    text_color:
      name: Text Color
      description: Select the Text color
      selector:
        color_rgb:
      default: [255, 255, 255]
    show_rainbow:
      name: Rainbow Colors
      description: Should the notification be shown in Rainbow colors?
      selector:
        boolean:
      default: false
    repeat:
      name: Repeat
      description: Sets how many times the text should be scrolled through the matrix before the app ends. If the value is -1, the duration will be taken into account instead.
      default: "-1"
    duration:
      name: Duration (in seconds)
      description: Sets how long the app should be displayed. 0 is global app time.
      default: "0"
    lifetime:
      name: Lifetime (in seconds)
      description: Sets how long the app should stay alive before it gets removed from the app cycle automatically. 0 is infinite lifetime.
      default: "0"
    switch_to_app:
      name: Switch to app on value change
      description: Should the clock switch to the app immediately when the value of the sensor changes?
      selector:
        boolean:
      default: false
    scroll:
      name: Scroll the notification?
      description: Enables text scrolling
      selector:
        boolean:
      default: true
    scrollspeed:
      name: Scroll Speed Percentage
      description: Modifies the scrollspeed. You need to enter a percentage value.
      selector:
        number:
          mode: slider
          min: 0
          max: 100
      default: 100
    effect:
      name: Effect
      description: Select a background effect (optional).
      selector:
        select:
          options:
            - label: "None"
              value: ""
            - label: "BrickBreaker"
              value: "BrickBreaker"
            - label: "Checkerboard"
              value: "Checkerboard"
            - label: "ColorWaves"
              value: "ColorWaves"
            - label: "Fireworks"
              value: "Fireworks"
            - label: "LookingEyes"
              value: "LookingEyes"
            - label: "Matrix"
              value: "Matrix"
            - label: "MovingLine"
              value: "MovingLine"
            - label: "PingPong"
              value: "PingPong"
            - label: "Pacifica"
              value: "Pacifica"
            - label: "Plasma"
              value: "Plasma"
            - label: "PlasmaCloud"
              value: "PlasmaCloud"
            - label: "Radar"
              value: "Radar"
            - label: "Ripple"
              value: "Ripple"
            - label: "Snake"
              value: "Snake"
            - label: "SwirlIn"
              value: "SwirlIn"
            - label: "SwirlOut"
              value: "SwirlOut"
            - label: "TheaterChase"
              value: "TheaterChase"
            - label: "TwinklingStars"
              value: "TwinklingStars"
          mode: dropdown
      default: ""

mode: queued

trigger:
  - platform: state
    entity_id: !input toggle_helper
    to: "on"
    id: "On"
  - platform: state
    entity_id: !input toggle_helper
    to: "off"
    id: "Off"
  - platform: state
    entity_id: !input my_sensor
    id: Changes

variables:
  device_ids: !input awtrix_displays
  devices: >-
    {% macro get_device(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0] | default('unknown')) }}
    {% endmacro %}

    {% set ns = namespace(devices=[]) %}
    {% for device_id in device_ids %}
      {% set device=get_device(device_id)|replace(' ','')|replace('\n','') %}
      {% set ns.devices = ns.devices + [ device ] %}
    {% endfor %}
    {{ ns.devices | reject('match','unavailable|unknown') | list }}
  my_sensor: !input my_sensor
  push_icon: !input push_icon
  text_case: !input text_case
  show_rainbow: !input show_rainbow
  background_color: !input background_color
  text_color: !input text_color
  my_toggle_helper: toggle_helper
  my_repeat: !input repeat
  my_duration: !input duration
  show_text: !input show_text
  language: !input language
  show_temperature: !input show_temperature
  show_windspeed: !input show_windspeed
  show_humidity: !input show_humidity
  dutch: >
    {%- set translation = { 
                      'clear-night':'helder',
                      'cloudy':'bewolkt',
                      'fog':'mist',
                      'hail':'hagel',
                      'lightning':'bliksem',
                      'partlycloudy':'halfbewolkt',
                      'pouring':'regen',
                      'rainy':'regenachtig',
                      'snowy-rainy':'sneeuw/regen',
                      'snowy':'sneeuw',
                      'sunny':'zonnig',
                      'windy':'wind'
                      } -%}
    {{ translation[states(my_sensor)] }}
  german: >
    {%- set translation = { 
                      'clear-night':'klare nacht',
                      'cloudy':'wolkig',
                      'fog':'nebel',
                      'hail':'hagel',
                      'lightning':'blitz',
                      'partlycloudy':'teilweise wolkig',
                      'pouring':'gießen',
                      'rainy':'regnerisch',
                      'snowy-rainy':'verschneit-regnerisch',
                      'snowy':'schnee',
                      'sunny':'sonnig',
                      'windy':'windig'
                      } -%}
    {{ translation[states(my_sensor)] }}
  french: >
    {%- set translation = { 
                      'clear-night':'nuit claire',
                      'cloudy':'nuageux',
                      'fog':'brouillard',
                      'hail':'grêle',
                      'lightning':'foudre',
                      'partlycloudy':'partiellement nuageux',
                      'pouring':'verser',
                      'rainy':'pluvieux',
                      'snowy-rainy':'neigeux et pluvieux',
                      'snowy':'neigeux',
                      'sunny':'ensoleillé',
                      'windy':'venteux'
                      } -%}
    {{ translation[states(my_sensor)] }}
  spanish: >
    {%- set translation = { 
                      'clear-night':'noche clara',
                      'cloudy':'nublado',
                      'fog':'niebla',
                      'hail':'granizo',
                      'lightning':'iluminación',
                      'partlycloudy':'parcialmente nublado',
                      'pouring':'torrencial',
                      'rainy':'lluvioso',
                      'snowy-rainy':'nevado-lluvioso',
                      'snowy':'nevado',
                      'sunny':'soleado',
                      'windy':'ventoso'
                      } -%}
    {{ translation[states(my_sensor)] }}
  portugese: >
    {%- set translation = { 
                      'clear-night':'noite clara',
                      'cloudy':'nublado',
                      'fog':'névoa',
                      'hail':'saudação',
                      'lightning':'raio',
                      'partlycloudy':'parcialmente nublado',
                      'pouring':'derramando',
                      'rainy':'chuvoso',
                      'snowy-rainy':'nevado-chuvoso',
                      'snowy':'Nevado',
                      'sunny':'ensolarado',
                      'windy':'ventoso'
                      } -%}
  polish: >
    {%- set translation = { 
                      'clear-night':'czysta noc',
                      'cloudy':'pochmurny',
                      'fog':'mgła',
                      'hail':'grad',
                      'lightning':'Błyskawica',
                      'partlycloudy':'częściowe zachmurzenie',
                      'pouring':'zsyp',
                      'rainy':'deszczowy',
                      'snowy-rainy':'śnieżno-deszczowy',
                      'snowy':'śnieżny',
                      'sunny':'słoneczny',
                      'windy':'wietrzny'
                      } -%}
    {{ translation[states(my_sensor)] }}
  my_text: >
    {%- if (show_text) -%}
      {%- if language == 'en' -%}
        {{ states(my_sensor) }}
      {%- elif language == 'nl' -%}
        {{ dutch }}
      {%- elif language == 'de' -%}
        {{ german }}
      {%- elif language == 'fr' -%}
        {{ french }}
      {%- elif language == 'es' -%}
        {{ spanish }}
      {%- elif language == 'pt' -%}
        {{ portugese }}
      {%- elif language == 'pl' -%}
        {{ polish }}
      {%- endif -%}
    {%- endif -%}
    {%- if (show_temperature) -%}
      {{ ' ' }}{{ state_attr(my_sensor, 'temperature') }}{{state_attr(my_sensor, "temperature_unit")}}
    {%- endif -%}
    {%- if (show_windspeed) -%}
      {{ ' - ' }}{{ state_attr(my_sensor, "wind_speed" ) }}{{ state_attr(my_sensor, "wind_speed_unit") }}
    {%- endif -%}
    {%- if (show_humidity) -%}
      {{ ' - ' }}{{ state_attr(my_sensor, "humidity" ) }}%
    {%- endif -%}
  my_lifetime: !input lifetime
  switch_to_app: !input switch_to_app
  app_name: >
    {{ my_sensor | trim }}
  scrolling: !input scroll
  scroll_speed: !input scrollspeed
  effect: !input effect

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "On"
        sequence:
          - repeat:
              for_each: "{{ devices }}"
              sequence:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{repeat.item}}/custom/{{app_name}}"
                    payload: |-
                      {   
                        "text": "{{ my_text }}",
                        "color": {{text_color}},
                        "background": {{ background_color }},
                        "icon": "{{ states(my_sensor) }}",
                        "textCase": {{ text_case }},
                        "pushIcon": {{ push_icon }},
                        "rainbow": {{ iif(show_rainbow, "true", "false") }},
                        "repeat": {{ my_repeat }},
                        "duration": {{ my_duration }},
                        "lifetime": {{ my_lifetime }},
                        "noScroll": {{ iif(scrolling, "false", "true") }},
                        "scrollSpeed": {{ scroll_speed }},
                        "effect": "{{ effect }}"
                      }
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{repeat.item}}/switch"
                    payload: |-
                      {   
                        "name": "{{app_name}}"
                      }
      - conditions:
          - condition: trigger
            id: "Off"
        sequence:
          - repeat:
              for_each: "{{ devices }}"
              sequence:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{repeat.item}}/custom/{{app_name}}"
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: Changes
              - condition: state
                entity_id: !input toggle_helper
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input my_sensor
                    state:
                      - unavailable
                      - unknown
        sequence:
          - repeat:
              for_each: "{{ devices }}"
              sequence:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{repeat.item}}/custom/{{app_name}}"
                    payload: |-
                      {   
                        "text": "{{ my_text }}",
                        "color": {{text_color}},
                        "background": {{ background_color }},
                        "icon": "{{ states(my_sensor) }}",
                        "textCase": {{ text_case }},
                        "pushIcon": {{ push_icon }},
                        "rainbow": {{ iif(show_rainbow, "true", "false") }},
                        "repeat": {{ my_repeat }},
                        "duration": {{ my_duration }},
                        "lifetime": {{ my_lifetime }},
                        "noScroll": {{ iif(scrolling, "false", "true") }},
                        "scrollSpeed": {{ scroll_speed }},
                        "effect": "{{ effect }}"
                      }
                - condition: template
                  value_template: "{{ switch_to_app == true }}"
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{repeat.item}}/switch"
                    payload: |-
                      {   
                        "name": "{{app_name}}"
                      }
