action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - bettFloOn
    sequence:
    - data: {}
      service: input_boolean.turn_on
      target:
        entity_id:
        - input_boolean.florian_im_bett
  - conditions:
    - condition: trigger
      id:
      - bettFloOff
    sequence:
    - data: {}
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.florian_im_bett
  - conditions:
    - condition: trigger
      id:
      - threeMinuteBedOff
    sequence:
    - device_id: 496f1ee059a80ce3be70b9a32eb69778
      domain: light
      entity_id: light.bett
      type: turn_off
    - device_id: 58ad2259e60395f647695636a43a16c8
      domain: switch
      entity_id: switch.steckdose_tv_bank_wohnzimmer
      type: turn_off
    - device_id: aaad1ea70b31b2d4cdd44583712720b2
      domain: switch
      entity_id: switch.steckdose_schreibtisch
      type: turn_off
    - device_id: 31cea6ff31b5a821a4fa741d0c987b4d
      domain: switch
      entity_id: switch.steckdose_badezimmer
      type: turn_off
    - device_id: 90c331ab3f9f2e741e5bb1be8bd89c5d
      domain: switch
      entity_id: switch.steckdose_dyson
      type: turn_off
    - data: {}
      service: switch.turn_off
      target:
        device_id: 8d9991a5dd07654891a5cf3a476cba07
alias: Bett
condition: []
description: ''
id: '1677005798686'
mode: single
trigger:
- entity_id:
  - binary_sensor.bed_sensor_bett_links
  for:
    hours: 0
    minutes: 0
    seconds: 0
  from: 'off'
  id: bettFloOn
  platform: state
  to: 'on'
- entity_id:
  - binary_sensor.bed_sensor_bett_links
  for:
    hours: 0
    minutes: 0
    seconds: 0
  from: 'on'
  id: bettFloOff
  platform: state
  to: 'off'
- entity_id:
  - timer.3_minuten_bett
  from: active
  id: threeMinuteBedOff
  platform: state
  to: idle
