action:
- data: {}
  service: input_boolean.turn_on
  target:
    entity_id:
    - input_boolean.steffi_angst
    - input_boolean.steffi_herz
    - input_boolean.steffi_babypille
    - input_boolean.steffi_migrane
alias: 'Boolean: Reset Mitternacht'
condition: []
description: Staubsauger Einmal Täglich
id: '1678799484819'
mode: single
trigger:
- at: 00:00:00
  platform: time
