action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - badezimmerWaterOn
    - condition: state
      entity_id: input_boolean.winter_mode
      state: 'on'
    sequence: []
  - conditions:
    - condition: trigger
      id:
      - badezimmerWaterOn
    - condition: device
      device_id: 507d523084cd0d287b97a79f906aef8d
      domain: light
      entity_id: f9898315524e3aee17127ffd4c15b5db
      type: is_on
    sequence:
    - data:
        brightness_pct: 30
      service: light.turn_on
      target:
        device_id: 507d523084cd0d287b97a79f906aef8d
  - conditions:
    - condition: trigger
      id:
      - badezimmerWaterOn
    sequence:
    - data:
        volume_level: 0.7
      service: media_player.volume_set
      target:
        device_id: e44130d7e1ed3ec3b0a00e119c9f9e64
- choose:
  - conditions:
    - condition: trigger
      id:
      - badezimmerWaterOff
    - condition: state
      entity_id: input_boolean.winter_mode
      state: 'on'
    sequence: []
  - conditions:
    - condition: trigger
      id:
      - badezimmerWaterOff
    - condition: device
      device_id: 507d523084cd0d287b97a79f906aef8d
      domain: light
      entity_id: f9898315524e3aee17127ffd4c15b5db
      type: is_on
    sequence:
    - data:
        brightness_pct: 100
      service: light.turn_on
      target:
        device_id: 507d523084cd0d287b97a79f906aef8d
  - conditions:
    - condition: trigger
      id:
      - badezimmerWaterOff
    sequence:
    - data:
        volume_level: 0.36
      service: media_player.volume_set
      target:
        device_id: e44130d7e1ed3ec3b0a00e119c9f9e64
alias: Duschen
condition: []
description: ''
id: '1691499965189'
mode: single
trigger:
- device_id: f57e11fe2c1f1f570e8ac1a451700193
  domain: binary_sensor
  entity_id: da4dd570201aa966762457445728876e
  for:
    hours: 0
    minutes: 0
    seconds: 10
  id: badezimmerWaterOn
  platform: device
  type: moist
- device_id: f57e11fe2c1f1f570e8ac1a451700193
  domain: binary_sensor
  entity_id: da4dd570201aa966762457445728876e
  id: badezimmerWaterOff
  platform: device
  type: not_moist
