action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - reweOn
    sequence:
    - data:
        data:
          actions:
          - action: URI
            icon: sfsymbols:cart
            title: Zeige mir die Einkaufsliste
            uri: /shopping-list
        message: Hast du was auf deiner Einkaufsliste, was du vielleicht noch besorgen
          müsstest?
        title: Willkommen bei Rewe
      service: notify.mobile_app_florians_iphone
alias: Einkaufen
condition: []
description: ''
id: '1691589275176'
mode: single
trigger:
- entity_id: person.florian
  event: enter
  id: reweOn
  platform: zone
  zone: zone.rewe_kantstrasse
- command:
  - Ich gehe jetzt einkaufen
  - Ich gehe mal einkaufen
  - Ich gehe einkaufen
  - Ich bin mal einkaufen
  id: reweSentence
  platform: conversation
