action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - tvSchlafzimmerOn
    sequence:
    - device_id: 6c73301e52dd6dcbca19086b41a34e63
      domain: light
      entity_id: 9f660825ed28073a10dae2644091c8e6
      type: turn_off
    - device_id: fe77e96440ea5bd125bde57df02a005b
      domain: light
      entity_id: c0d9fd3b4aacf9d5b5a02d67e56ab0a1
      type: turn_off
    - device_id: efbc936ef67025b80589311a47c29a35
      domain: remote
      entity_id: f9fb56b2246d7619148afe44df6bedcc
      type: turn_on
- choose:
  - conditions:
    - condition: trigger
      id:
      - tvSchlafzimmerOff
    sequence:
    - device_id: efbc936ef67025b80589311a47c29a35
      domain: remote
      entity_id: f9fb56b2246d7619148afe44df6bedcc
      type: turn_off
alias: Fernseher Schlafzimmer
condition:
- after: sunset
  before: sunrise
  condition: sun
description: ''
id: '1671819328944'
mode: single
trigger:
- device_id: c59d71c186dd5113268a8d1e392e68b7
  domain: media_player
  entity_id: 4748d69b5a095c96044b7453983b2f60
  id: tvSchlafzimmerOn
  platform: device
  type: turned_on
- device_id: c59d71c186dd5113268a8d1e392e68b7
  domain: media_player
  entity_id: 4748d69b5a095c96044b7453983b2f60
  id: tvSchlafzimmerOff
  platform: device
  type: turned_off
