action:
- brightness_pct: 40
  device_id: d8c4a563740ad75c1264d8ea5a45f73e
  domain: light
  entity_id: light.decke_flur
  type: turn_on
- delay:
    hours: 0
    milliseconds: 0
    minutes: 1
    seconds: 0
- device_id: d8c4a563740ad75c1264d8ea5a45f73e
  domain: light
  entity_id: light.decke_flur
  type: turn_off
alias: 'Flur: Licht an wenn Tür auf'
condition:
- after: sunset
  after_offset: '1'
  before: sunrise
  condition: sun
description: ''
id: '1669632865548'
mode: single
trigger:
- device_id: a02d56ba8b08c82c59f4530165d45028
  domain: binary_sensor
  entity_id: 4117df274860b910c20a5ff969c8b8f4
  id: flurOn
  platform: device
  type: opened
