action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - kaffeemaschineOn
        sequence:
          - device_id: 031993d091ace5064c51fb0681918e2f
            domain: switch
            entity_id: 1a7e2f959d8c36322587a817c3a2d043
            type: turn_on
      - conditions:
          - condition: trigger
            id:
              - kaffeemaschineOff
        sequence:
          - device_id: 031993d091ace5064c51fb0681918e2f
            domain: switch
            entity_id: switch.steckdose_kaffeemaschine
            type: turn_off
alias: Kaffeemaschine morgens um 07:30 an
condition:
  - condition: state
    entity_id: sensor.people_home
    state: "1"
description: Für vier Stunden
id: "1674670778068"
mode: single
trigger:
  - at: 07:30:00
    id: kaffeemaschineOn
    platform: time
  - at: "11:30:00"
    id: kaffeemaschineOff
    platform: time
