action:
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1
    message: Es wurde Bewegung entdeckt!
    title: ALARM ⚠️
  service: notify.mobile_app_florians_iphone
alias: 'Sicherheit: Bewegung erkannt'
condition:
- condition: state
  entity_id: sensor.people_home
  state: '0'
- condition: state
  entity_id: vacuum.roborock_s7_maxv
  state: docked
description: ''
id: '1691747640340'
mode: single
trigger:
- entity_id:
  - binary_sensor.motion_detected
  from: 'off'
  platform: state
  to: 'on'
