action:
- parallel:
  - device_id: 36a22733000aafdf6981ae28050acce6
    domain: switch
    entity_id: 9f3df5bcd72d18271a9c756a3e74a615
    type: turn_off
  - device_id: 3f3b82e0e25c8dae98f62ab1589ba2ca
    domain: switch
    entity_id: 7f3a644d010f80177ccd87f3d8915a5a
    type: turn_off
  - device_id: 478b9723de0593d7ecd82df10b431d50
    domain: switch
    entity_id: fba8f3766a6d41db9350ef9b99cc0fa7
    type: turn_on
- delay:
    hours: 0
    milliseconds: 0
    minutes: 0
    seconds: 20
- device_id: 107bc2a015d51fadd9d94ff04a352037
  domain: switch
  entity_id: cadfec9848a0910ae75dd30429f1c044
  type: turn_on
alias: 'Täglich: Schlafzimmer Steckdosen An'
condition: []
description: Luftreiniger Schlafzimmer
id: '1667647447637'
mode: single
trigger:
- at: 09:00:00
  platform: time
