action:
- device_id: b5c99c551f5157c833050ed2a812fa68
  domain: cover
  entity_id: cover.ikea_rollo_fensterbank_links_wohnzimmer
  type: open
- device_id: c0238df3821a546d59533f8cea51734b
  domain: cover
  entity_id: cover.ikea_rollo_fensterbank_rechts_wohnzimmer
  type: open
alias: Taster Wohnzimmer Rollos Öffnen
condition: []
description: ''
id: '1684774987339'
mode: single
trigger:
- device_id: 82fc44b6345e0bd01175085d8cf4bb9d
  discovery_id: 0xb4e3f9fffe6bf4b5 action_open
  domain: mqtt
  platform: device
  subtype: open
  type: action
