action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - fanOn
    sequence:
    - data:
        percentage: 60
      service: fan.turn_on
      target:
        entity_id: fan.ventilator
  - conditions:
    - condition: trigger
      id:
      - fanOff
    sequence:
    - data: {}
      service: fan.turn_off
      target:
        entity_id: fan.ventilator
alias: Ventilator
condition:
- after: 07:00:00
  before: '22:00:00'
  condition: time
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
  - sat
  - sun
- condition: state
  entity_id: input_boolean.ventilator
  state: 'on'
description: 'An: Wenn über 26 Grad

  Aus: Wenn unter 24 Grad'
id: '1686557247104'
mode: single
trigger:
- above: 26
  entity_id: sensor.temperatur_wohnzimmer
  id: fanOn
  platform: numeric_state
- above: 2
  below: 24
  entity_id: sensor.temperatur_wohnzimmer
  id: fanOff
  platform: numeric_state
