action:
- data:
    media_content_id: media-source://tts/cloud?message=Vergiss+nicht+nicht%2C+die+Waschmaschine+auszur%C3%A4umen.&language=de-DE&voice=KatjaNeural
    media_content_type: provider
  metadata:
    children_media_class: null
    media_class: app
    navigateIds:
    - {}
    - media_content_id: media-source://tts
      media_content_type: app
    - media_content_id: media-source://tts/cloud?message=Vergiss+nicht+nicht%2C+die+Waschmaschine+auszur%C3%A4umen.&language=de-DE&voice=KatjaNeural
      media_content_type: provider
    thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
    title: Vergiss nicht nicht, die Waschmaschine auszuräumen.
  service: media_player.play_media
  target:
    entity_id: media_player.nest_kuche
alias: Waschmaschine
condition:
- condition: state
  entity_id: sensor.people_home
  state: '1'
description: ''
id: '1667905476778'
mode: single
trigger:
- entity_id:
  - binary_sensor.aeg_lavamat_6000_series
  for:
    hours: 2
    minutes: 0
    seconds: 0
  from: 'on'
  platform: state
  to: 'off'
