web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  ddl-warez:
    rss: https://ddl-warez.cc/feed/
    download: /data
    series:
      - some series 1
      - some series 2

schedules: no
