---
- platform: bayesian
  name: Kochen
  prior: 0
  probability_threshold: 6
  observations:
    - platform: template
      prob_given_true: 2
      prob_given_false: 0
      value_template: >
        {{ states('sensor.aqara_thermo_kuche_temperature') | int > states('sensor.aqara_thermo_flur_temperature') | int + 3 }}
    - platform: state
      prob_given_true: 3
      prob_given_false: 0
      to_state: on
      entity_id: binary_sensor.hlk_kuche_belegung
    - platform: state
      prob_given_true: 2
      prob_given_false: 0
      to_state: on
      entity_id: switch.steckdose_optigrill
    - platform: state
      prob_given_true: 2
      prob_given_false: 0
      to_state: on
      entity_id: switch.steckdose_hlf
    - platform: template
      prob_given_true: 2
      prob_given_false: 0
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.aqara_contact_kuhlschrank_contact.last_changed)) < 900 }}
