- platform: template
  sensors:
    power_current:
      friendly_name: "Power Current"
      unit_of_measurement: W
      device_class: power
      value_template: >-
        {{ states('sensor.shelly_em3_channel_a_power')|float + states('sensor.shelly_em3_channel_b_power')|float + states('sensor.shelly_em3_channel_c_power')|float }}
      availability_template: "{{
        [ states('sensor.shelly_em3_channel_a_power'),
        states('sensor.shelly_em3_channel_b_power'),
        states('sensor.shelly_em3_channel_c_power')
        ] | map('is_number') | min
        }}"

    power_import:
      friendly_name: "Power Import"
      unit_of_measurement: W
      device_class: power
      value_template: >-
        {% if (states('sensor.shelly_em3_channel_a_power')|float + states('sensor.shelly_em3_channel_b_power')|float + states('sensor.shelly_em3_channel_c_power')|float) > 0 %}
          {{ states('sensor.shelly_em3_channel_a_power')|float + states('sensor.shelly_em3_channel_b_power')|float + states('sensor.shelly_em3_channel_c_power')|float }}
        {% else %}
          {{ 0 }}
        {% endif %}
      availability_template: "{{
        [ states('sensor.shelly_em3_channel_a_power'),
        states('sensor.shelly_em3_channel_b_power'),
        states('sensor.shelly_em3_channel_c_power')
        ] | map('is_number') | min
        }}"

    power_export:
      friendly_name: "Power Export"
      unit_of_measurement: W
      device_class: power
      value_template: >-
        {% if (states('sensor.shelly_em3_channel_a_power')|float + states('sensor.shelly_em3_channel_b_power')|float + states('sensor.shelly_em3_channel_c_power')|float) < 0 %}
          {{ (states('sensor.shelly_em3_channel_a_power')|float + states('sensor.shelly_em3_channel_b_power')|float + states('sensor.shelly_em3_channel_c_power')|float) * -1 }}
        {% else %}
          {{ 0 }}
        {% endif %}
      availability_template: "{{
        [ states('sensor.shelly_em3_channel_a_power'),
        states('sensor.shelly_em3_channel_b_power'),
        states('sensor.shelly_em3_channel_c_power')
        ] | map('is_number') | min
        }}"

    power_consumption:
      friendly_name: "Power Consumption"
      unit_of_measurement: W
      device_class: power
      value_template: >-
        {% if (states('sensor.power_export')|float(0)) > 0 and (states('sensor.power_solargen')|float(0) - states('sensor.power_export')|float(0)) < 0 %}
          {{ 0 }}    
        {% elif (states('sensor.power_export')|float(0)) > 0 and (states('sensor.power_solargen')|float(0) - states('sensor.power_export')|float(0)) > 0 %}
          {{ (states('sensor.power_solargen')|float(0)) - states('sensor.power_export')|float(0) }}    
        {% else %}
          {{ states('sensor.power_import')|float(0) + states('sensor.power_solargen')|float(0) }}
        {% endif %}

    power_solargen:
      friendly_name: "Power Solar Generation"
      unit_of_measurement: W
      device_class: power
      value_template: >-
        {% if (states('sensor.shelly_bkw_power')|float(0)) > 0 %}
          {{ (states('sensor.shelly_bkw_power')|float(0)) }}
        {% else %}
          {{ 0 }}
        {% endif %}

- platform: integration
  source: sensor.power_import
  name: energy_import_sum
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.power_export
  name: energy_export_sum
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.power_consumption
  name: energy_consumption_sum
  unit_prefix: k
  round: 2
  method: left
