---
- platform: template
  sensors:
    current_media_player_image:
      value_template: >
        {% if is_state("sensor.current_media_player", "playing") and is_state_attr("sensor.current_media_player", "media_content_type", "music") -%}
          {{ state_attr('sensor.current_media_player') }}
        {%- endif %}
