---
- platform: template
  sensors:
    current_media_player_track:
      value_template: >
        {% set activePlayer = states('sensor.current_media_player') %}
        {% if is_state(activePlayer, "playing") and is_state_attr(activePlayer, "media_content_type", "music") -%}
          {{ state_attr(activePlayer, 'media_title') }}
        {%- endif %}
