- platform: history_stats
  name: historystats_florian_away_minutes
  entity_id: person.florian
  state: "not_home"
  type: time
  end: "{{ now().replace(hour=0, minute=0, second=0) }}"
  duration:
    minutes: 1
