---
- platform: template
  sensors:
    greeting:
      friendly_name: "Greeting"
      value_template: >
        {% set greetings = [
          "Good morning! A new day full of possibilities awaits.",
          "Rise and shine! Embrace the opportunities of today.",
          "Good morning! Let your light shine bright today.",
          "Wake up and greet the day with joy and courage.",
          "Good morning! Today is a canvas awaiting your masterpiece.",
          "Rise and shine! A fresh start begins now.",
          "Good morning! Make every moment count.",
          "Step into the day with confidence and optimism.",
          "Good morning! Today holds endless potential.",
          "Rise and shine! The world is yours to explore.",
          "Good morning! Each day is a new adventure.",
          "Embrace the dawn of a beautiful new day.",
          "Good morning! Let passion fuel your journey today.",
          "Wake up to the promise of a wonderful day ahead.",
          "Good morning! Today is the day to achieve your dreams.",
          "Rise and shine! Seize the day with enthusiasm.",
          "Good morning! Let inspiration guide your steps.",
          "Welcome the new day with an open heart and mind.",
          "Good morning! Today is your day to make a difference.",
          "Rise and shine! The future is bright and filled with hope.",
          "Good morning! Embrace the challenges and joys of today.",
          "Start your day with a smile and positive energy.",
          "Good morning! May today be filled with happiness and success.",
          "Rise and shine! A fresh journey begins with the morning sun.",
          "Good morning! Let every moment inspire you.",
          "Wake up, it's a new day to shine and succeed.",
          "Good morning! Today is the perfect day to start afresh.",
          "Embrace today with courage and passion.",
          "Good morning! Fill your day with creativity and joy.",
          "Rise and shine! Let your dreams set sail today.",
          "Good morning! A brand new day awaits your brilliance.",
          "Start your morning with gratitude and positivity.",
          "Good morning! Today's opportunities are as vast as the sky.",
          "Rise and shine! Let the morning sun energize your spirit.",
          "Good morning! Every day is a chance to rewrite your story.",
          "Greet the day with hope, passion, and determination.",
          "Good morning! Embrace the magic of a new beginning.",
          "Rise and shine! Today is a chapter of endless promise.",
          "Good morning! Let your ambitions soar high.",
          "Wake up and witness the beauty of a new sunrise.",
          "Good morning! Every moment is a stepping stone to greatness.",
          "Embrace the day with zest and an open heart.",
          "Good morning! Let your inner strength lead the way.",
          "Rise and shine! Today is a gift waiting to be unwrapped.",
          "Good morning! May your day be filled with positive surprises.",
          "Welcome the morning with a spirit full of possibilities.",
          "Good morning! Let today inspire your journey.",
          "Rise and shine! New challenges lead to new achievements.",
          "Good morning! Seize the day and make your dreams come true.",
          "Wake up and embrace the beauty of a fresh start."
        ] %}
        {{ greetings | random }}
