---
- platform: feedparser
  name: Heise Security News
  feed_url: "https://www.heise.de/security/rss/news.rdf"
  date_format: "%a, %d %b %Y %H:%M:%S %Z"
  scan_interval:
    hours: 3
  inclusions:
    - title
  exclusions:
    - link
    - description
    - image
    - published
  show_topn: 1
