---
- platform: influxdb
  api_version: 2
  host: 10.182.1.206
  port: 8086
  organization: !secret unfluxdb_org_id
  #bucket: homeassistant
  token: !secret influxdb_token
  queries_flux:
    - group_function: last
      imports:
        - strings
      name: "Heartrate Florian"
      query: >
        from(bucket: "homeassistant")
          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
          |> filter(fn: (r) => r["_measurement"] == "bpm")
          |> filter(fn: (r) => r["entity_id"] == "healthexport_heart_rate")
          |> filter(fn: (r) => r["source"] == "HA")
          |> filter(fn: (r) => r["_field"] == "value")
          |> filter(fn: (r) => r["domain"] == "hae")
          |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
          |> yield(name: "last")
    - group_function: last
      imports:
        - strings
      name: "Heartrate Florian"
      query: >
        from(bucket: "homeassistant")
          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
          |> filter(fn: (r) => r["_measurement"] == "bpm")
          |> filter(fn: (r) => r["entity_id"] == "healthexport_heart_rate")
          |> filter(fn: (r) => r["source"] == "HA")
          |> filter(fn: (r) => r["_field"] == "value")
          |> filter(fn: (r) => r["domain"] == "hae")
          |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
          |> yield(name: "last")