- platform: template
  sensors:
    any_light_on:
      friendly_name: Irgendein Licht An
      value_template: >
        {% set badezimmer_lights_on = is_state("light.badezimmer", "on") %}
        {% set schlafzimmer_lights_on = is_state("light.schlafzimmer", "on") %}
        {% set wohnzimmer_lights_on = is_state("light.wohnzimmer", "on") %}
        {% set buero_lights_on = is_state("light.buro", "on") %}
        {% set flur_lights_on = is_state("light.flur", "on") %}
        {% set kueche_lights_on = is_state("light.kuche", "on") %}
        {{ badezimmer_lights_on or schlafzimmer_lights_on or wohnzimmer_lights_on or buero_lights_on or flur_lights_on or kueche_lights_on }}
