- platform: template
  sensors:
    current_lights_on:
      friendly_name: Lights at this moment
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.wohnzimmer,
          states.light.flur,
          states.light.kuche,
          states.light.kinderzimmer,
          states.light.buro,
          states.light.schlafzimmer,
          states.light.badezimmer,
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}
