---
- platform: template
  sensors:
    location_florian:
      value_template: >
        {% if is_state('device_tracker.pixel_9', 'home') %}
          Zuhause
        {% elif is_state("device_tracker.pixel_9", "not_home") %}
          Unterwegs
        {% else %}
          {{ states("device_tracker.pixel_9") }}
        {% endif %}
    location_steffi_color:
      value_template: >
        {% if is_state("device_tracker.pixel_9", "home") %}
          green
        {% elif is_state("device_tracker.pixel_9", "Steffi Zuhause") %}
          pink
        {%- else -%}
          red
        {%- endif -%}
    location_steffi_icon:
      value_template: >
        {% if is_state("device_tracker.pixel_9", "home") %}
          mdi:home
        {% elif is_state("device_tracker.pixel_9", "Steffi Zuhause") %}
          mdi:home-heart
        {%- else -%}
          mdi:home-remove
        {%- endif %}
