- platform: template
  sensors:
    macs_camera_on:
      friendly_name: "Mac Kamera An"
      value_template: >
        {% if is_state('binary_sensor.mac_mini_camera_in_use', 'on') or is_state('binary_sensor.macbook_pro_camera_in_use', 'on') %}
          true
        {% else %}
          false
        {% endif %}
