---
- platform: mold_indicator
  indoor_temp_sensor: sensor.aqara_thermo_wohnzimmer_temperature
  indoor_humidity_sensor: sensor.aqara_thermo_wohnzimmer_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
  name: Wohnzimmer Schimmel Warnung

- platform: mold_indicator
  indoor_temp_sensor: sensor.aqara_thermo_schlafzimmer_temperature
  indoor_humidity_sensor: sensor.aqara_thermo_schlafzimmer_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
  name: Schlafzimmer Schimmel Warnung

- platform: mold_indicator
  indoor_temp_sensor: sensor.aqara_thermo_kuche_temperature
  indoor_humidity_sensor: sensor.aqara_thermo_kuche_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
  name: Küche Schimmel Warnung

- platform: mold_indicator
  indoor_temp_sensor: sensor.aqara_thermo_flur_temperature
  indoor_humidity_sensor: sensor.aqara_thermo_flur_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
  name: Flur Schimmel Warnung

- platform: mold_indicator
  indoor_temp_sensor: sensor.aqara_thermo_badezimmer_temperature
  indoor_humidity_sensor: sensor.aqara_thermo_badezimmer_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
  name: Badezimmer Schimmel Warnung

- platform: mold_indicator
  indoor_temp_sensor: sensor.aqara_thermo_kinderzimmer_temperature
  indoor_humidity_sensor: sensor.aqara_thermo_kinderzimmer_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
  name: Kinderzimmer Schimmel Warnung
