---
- platform: rest
  name: Paperless Documents
  resource: https://paperless.wartner.cloud/api/documents/
  method: GET
  headers:
    Authorization: !secret paperless_token
  value_template: "{{ value_json.count }}"
  scan_interval: 300
  unique_id: paperless_documents
  unit_of_measurement: Dokumente

- platform: rest
  name: Paperless Inbox
  resource: https://paperless.wartner.cloud/api/tags/7/
  method: GET
  headers:
    Authorization: !secret paperless_token
  value_template: "{{ value_json.document_count }}"
  scan_interval: 60
  unique_id: paperless_inbox
  unit_of_measurement: Dokumente
