- platform: template
  sensors:
    people_home:
      friendly_name: "Jemand Zuhause"
      unit_of_measurement: "home"
      value_template: >
        {{ states['person'] | selectattr('state','eq','home') | list | count }}
