---
- platform: template
  sensors:
    random_morning_action_time:
      friendly_name: "Random Morning Action Time"
      value_template: >
        {% set total_minutes = range(390,511) | random %}
        {% set hours = total_minutes // 60 %}
        {% set minutes = total_minutes % 60 %}
        {{ "%02d:%02d:00" | format(hours, minutes) }}
