---
- platform: template
  sensors:
    random_afternoon_action_time:
      friendly_name: "Random Afternoon Action Time"
      value_template: >
        {% set total_minutes = range(885,901) | random %}
        {% set hours = total_minutes // 60 %}
        {% set minutes = total_minutes % 60 %}
        {{ "%02d:%02d:00" | format(hours, minutes) }}
