---
# Template sensors have been moved to custom_configs/templates/power_sensors.yaml
# Only integration platform sensors remain here

- platform: integration
  source: sensor.power_import
  name: energy_import_sum
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.power_export
  name: energy_export_sum
  unit_prefix: k
  round: 2
  method: left
