---
- platform: template
  sensors:
    tag_de:
      value_template: "{{ ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'][now().weekday()] }}"
    monat_de:
      value_template: "{% set months = ['Januar', 'Februar', 'März', 'April', 'Main', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'] %} {{ now().day | string + ' ' + months[now().month-1]}}"
