- platform: template
  sensors:
    tv_schlafzimmer_volume:
      value_template: >
        {{ state_attr("media_player.tv_schlafzimmer", "volume_level") }}
      unit_of_measurement: "%"

    tv_wohnzimmer_volume:
      value_template: >
        {{ state_attr("media_player.tv_wohnzimmer", "volume_level") }}
      unit_of_measurement: "%"

    sonos_ray_volume:
      value_template: >
        {{ state_attr("media_player.sonos_ray", "volume_level") }}
      unit_of_measurement: "%"

    echo_show_wohnzimmer_volume:
      value_template: >
        {{ state_attr("media_player.echo_show_wohnzimmer", "volume_level") }}
      unit_of_measurement: "%"

    echo_flur_volume:
      value_template: >
        {{ state_attr("media_player.echo_flur", "volume_level") }}
      unit_of_measurement: "%"

    echo_schlafzimmer_volume:
      value_template: >
        {{ state_attr("media_player.echo_schlafzimmer", "volume_level") }}
      unit_of_measurement: "%"

    echo_badezimmer_volume:
      value_template: >
        {{ state_attr("media_player.echo_badezimmer", "volume_level") }}
      unit_of_measurement: "%"

    echo_buero_volume:
      value_template: >
        {{ state_attr("media_player.echo_buero", "volume_level") }}
      unit_of_measurement: "%"

    echo_jonas_volume:
      value_template: >
        {{ state_attr("media_player.echo_von_jonas", "volume_level") }}
      unit_of_measurement: "%"
