- platform: min_max
  name: Temperature mean
  type: mean
  entity_ids:
    - sensor.temperatur_wohnzimmer
    - sensor.temperatur_kueche
    - sensor.temperatur_schlafzimmer
    - sensor.temperatur_balkon
    - sensor.temperatur_kinderzimmer
    - sensor.temperatur_flur
    - sensor.temperatur_badezimmer
