substitutions:
  node_name: bt-proxy-schlafzimmer
  friendly_name: BT Proxy Schlafzimmer

api:
  encryption:
    key: "ko8prsmAAnCe5/UL++9RND+lO6iS6PkaistqPGWnCpc="

packages:
  base: !include common/base_32.yaml
  ble: !include common/ble_gateway.yaml

wifi:
  manual_ip:
    static_ip: 10.182.1.44

web_server:
  version: 2
  include_internal: true