substitutions:
  name: bt-proxy-wz
  friendly_name: Bluetooth Proxy Wohnzimmer
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: s+kxY82dWeKcTHa2ZCcMsvdZMPqTUYlkry0wAngCYSo=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: restart
    name: "ESP Restart"