substitutions:
  name: esp32-bluetooth-proxy-cdc938
  friendly_name: Bluetooth Proxy cdc938
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: XhhWPI8IP+dyZYa6mNW//PmEHaRuXcvql9gXz0hlpks=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password