substitutions:
  node_name: peephole-esp32-cam
  friendly_name: Peephole ESP32 Cam

esp32:
  board: esp32dev
  framework:
    type: arduino

api:
  encryption:
    key: "pdfR8JnuDkzKoN4U3dQTukklgRojKnnN5mIGL1zSh48="

packages:
  base: !include common/base_32.yaml

wifi:
  manual_ip:
    static_ip: 10.182.1.65

esp32_camera:
  name: Camera
  external_clock:
    pin: GPIO0
    frequency: 8MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1280x1024
  jpeg_quality: 10
  max_framerate: 10fps
  idle_framerate: 1fps
  vertical_flip: false
  horizontal_mirror: false
  brightness: 2
  contrast: 1
  special_effect: none
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  wb_mode: auto

output:
  - platform: ledc
    channel: 2
    pin: GPIO4
    id: espCamLED
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33

light:
  - platform: monochromatic
    output: espCamLED
    name: light
  - platform: binary
    output: gpio_33
    name: led

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot