substitutions:
  system_name: automatic-plant-water
  friendly_name: Esph Watering D1
  relay_gpio: D2 #D5=GPIO14
  #dht22_gpio: D7
  #button_switch_gpio: D2
  soil_moisture_adc: A0

esphome:
  name: "${system_name}"
  
  friendly_name: automatic-plant-water

esp8266:
  board: nodemcu

logger:

web_server:
    port: 80

api:
  encryption:
    key: "aTbXdqRpo2bfGDo4LkLVTODvpDSox+TH2VljmelFNZw="

ota:
  password: "eff149aca4605bce30b8ee62c6cbe80f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Automatic-Plant-Water"
    password: "vsRfjszt49Yb"

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: "esph_${system_name}_version"
    on_value:
      then:
        - lambda: |-
            ESP_LOGD("main", "The current version is %s", x.c_str());
  - platform: wifi_info
    ip_address:
      name: esph_${system_name}_ip
    ssid:
      name: esph_${system_name}_ssid
    bssid:
      name: esph_${system_name}_bssid

switch:
  - platform: gpio
    id: relay
    restore_mode: ALWAYS_OFF
    name: "${system_name} Relay"
    pin: 
      number: $relay_gpio 
      inverted: True
    on_turn_on:
      then:
        # Do something
    on_turn_off:
      then:
        - homeassistant.service:        
            service: input_datetime.set_datetime
            data_template:          
              entity_id: "input_datetime.esph_${system_name}_triggered" 
              datetime: !lambda return id(homeassistant_time).now().strftime("%Y-%m-%d %H:%M:%S");
              
        - homeassistant.service:
            service: notify.html5_notification
            data:
              title: Plants Watered
            data_template:
              message: Plants were watered at {{ my_variable }}.
            variables:
              my_variable: |-
                return id(homeassistant_time).now().strftime("%Y-%m-%d %H:%M:%S");

  - platform: template
    name: "esph_${system_name}_timed_pump"
    id: timed_pump
    icon: "mdi:siren"
    lambda: !lambda |-    
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
    - switch.turn_on: relay
    - delay: !lambda return (id(zone1_pump_run_time).state * 1000);
    - switch.turn_off: relay
    - homeassistant.service:        
        service: input_datetime.set_datetime
        data_template:          
          entity_id: "input_datetime.esph_${system_name}_triggered" 
          datetime: !lambda return id(homeassistant_time).now().strftime("%Y-%m-%d %H:%M:%S");

  - platform: template
    name: "esph_${system_name}_pump"
    id: pump
    icon: "mdi:siren"
    lambda: !lambda |-    
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay
    - homeassistant.service:        
        service: input_datetime.set_datetime
        data_template:          
          entity_id: "input_datetime.esph_${system_name}_triggered" 
          datetime: !lambda return id(homeassistant_time).now().strftime("%Y-%m-%d %H:%M:%S");

sensor:
  - platform: homeassistant
    name: "Pump Runtime"
    entity_id: input_number.zone1_pump_run_time
    id: "zone1_pump_run_time"

  - platform: wifi_signal
    name: "esph_${system_name}_wifi_signal"
    update_interval: 300s

  - platform: uptime
    name: "esph_${system_name}_uptime"
    update_interval: 300s

  - platform: adc
    pin: $soil_moisture_adc
    name: "esph_${system_name}_soil_v"
    id: soil_v
    update_interval: 60s
    unit_of_measurement: 'v'
    accuracy_decimals: 2
    
  - platform: template
    name: "esph_${system_name}_soil_percent"
    id: soil_percent
    unit_of_measurement: '%'
    icon: "mdi:water-percent"
    update_interval: 60s
    accuracy_decimals: 0
      # Bryan Reading: 0.44 = in water, 0.84 = dry
    lambda: |-
      const float x = id(soil_v).state;
      if (x > 0.8) {
        return 0;
      } else if (x < 0.4) {
        return 100;
      } else {
        return (0.84 - x) / (0.84-0.44) * 100.0;
      }
      ESP_LOGD("main", "We hope soil value in volts is: %d", x); 