substitutions:
  node_name: bt-proxy-kuche
  friendly_name: BT Proxy Küche

api:
  encryption:
    key: "HNC/N5VUz3MqL9vZixKvnavSK4lx0NDyiAHhXWth6yY="

packages:
  base: !include common/base_32.yaml
  ble: !include common/ble_gateway.yaml

wifi:
  manual_ip:
    static_ip: 10.182.1.170

web_server:
  version: 2
  include_internal: true