substitutions:
  node_name: bt-proxy-flur
  friendly_name: BT Proxy Flur

api:
  encryption:
    key: "9KmkSjKIhxJwj8Mkc1zBZ6qr+VXMYvkw2ZpyBUYdyAw="

packages:
  base: !include common/base_32.yaml
  ble: !include common/ble_gateway.yaml
  wifi: !include common/wifi_fb.yaml

web_server:
  version: 2
  include_internal: true