substitutions:
  node_name: bt-proxy-wohnzimmer
  friendly_name: BT Proxy Wohnzimmer

api:
  encryption:
    key: "gGtk/Oi0A0tLk5UmCc0tNSPSGmaMljO4CABg5pXLinM="

packages:
  base: !include common/base_32.yaml
  ble: !include common/ble_gateway.yaml
  wifi: !include common/wifi_fb.yaml

web_server:
  version: 2
  include_internal: true