esphome:
  name: bt-proxy-schlafzimmer
  friendly_name: BT Proxy Schlafzimmer

api:
  encryption:
    key: "TY8gy3WZM2NaaYGgsiVcuyDo9L5i4HqIGSPiFJVzK2A="

packages:
  base: !include common/base_32.yaml
  ble: !include common/ble_gateway.yaml
  wifi: !include common/wifi_fb.yaml

web_server:
  version: 2
  include_internal: true