substitutions:
  name: "energy-display"
  friendly_name: "AMS-meter hvit"
  section1_end: "5"
  section2_end: "10"
  section3_end: "15"
  center_label: "7.5" # Setting this automatically is currently a work-in-progress!

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "kzz8qRLd9sMbQyFbA0ZdMzSqH4BqbfPrh5Ngg+yHTjY="

ota:
  - platform: esphome
    password: "ed4ace91554d3522bc58a79f794e2bf1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Energy-Display Fallback Hotspot"
    password: "NlykSrhoPGqZ"

captive_portal:

sensor:
  - platform: homeassistant
    id: kwh_live
    entity_id: sensor.shelly_em3_verbrauch_aktuell
    internal: True
    filters:
      - or:
        - delta: 100 # Send updates only when the change is more than 100 watts
        - timeout:
            timeout: 5min
            value: 0
      - multiply: 0.001 # Convert from Wh to kWh
    on_value:
      then:
        - script.execute: update_display
        - if: # Green font color if current usage is under 5 kWh
            condition:
              sensor.in_range: 
                 id: kwh_live
                 below: ${section1_end}
            then:
              - lvgl.label.update:
                  id: power_meter_text
                  text_color: 0x00FF00
        - if: # Yellow font color if current usage is 5-10 kWh
            condition:
              sensor.in_range: 
                 id: kwh_live
                 above: ${section1_end}
                 below: ${section2_end}
            then:
              - lvgl.label.update:
                  id: power_meter_text
                  text_color: 0xFFFF00
        - if: # Red font color if current usage is over 10 kWh
            condition:
              sensor.in_range: 
                 id: kwh_live
                 above: ${section2_end}
            then:
              - lvgl.label.update:
                  id: power_meter_text
                  text_color: 0xFF0000

  - platform: homeassistant
    id: kwh_today
    entity_id: sensor.energy_import_daily
    internal: True
    filters:
      - or:
        - delta: 0.5 # Send updates only when the change is more than 0.5 kWh
        - timeout:
            timeout: 90min
            value: 0
  - platform: homeassistant
    id: cost_today
    entity_id: sensor.strom_hittil_i_dag_kr
    internal: True
    filters:
      - or:
        - delta: 1 # Send updates only when the change is more than 1 kr
        - timeout:
            timeout: 150min
            value: 0
  - platform: homeassistant
    id: kwh_month
    entity_id: sensor.energy_import_monthly
    internal: True
    filters:
      - or:
        - delta: 0.5 # Send updates only when the change is more than 0.5 kWh
        - timeout:
            timeout: 90min
            value: 0
  - platform: homeassistant
    id: cost_month
    entity_id: sensor.strom_hittil_mnd_kr
    internal: True
    filters:
      - or:
        - delta: 1 # Send updates only when the change is more than 1 kr
        - timeout:
            timeout: 150min
            value: 0

spi:
  clk_pin: GPIO6
  mosi_pin: GPIO7

output:
  - platform: ledc
    pin:
      number: GPIO3
    id: backlight_output

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: back_light
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_off: 
      then:
        lvgl.pause

display:
  - platform: ili9xxx
    invert_colors: true
    id: lcd_display
    model: gc9a01a
    data_rate: 80MHz
    cs_pin: GPIO10
    dc_pin: GPIO2
    dimensions:
      width: 240
      height: 240
    update_interval: never
    auto_clear_enabled: false
    transform: # Configure to use it upside down. Remove transform-element to rotate 180
      mirror_x: true
      mirror_y: false
i2c:
  sda: 4
  scl: 5
  id: i2c_touch

touchscreen:
  platform: cst816
  id: my_touchscreen
  interrupt_pin: 0
  reset_pin: 1
  on_touch:
    then:
      - if: # If the LCD is switched off (controllable from the HASS-device), turn on display on first touch
          condition: lvgl.is_paused
          then:
            - lvgl.resume
            - lvgl.page.show: main_page
            - light.turn_on:
                id: back_light
          else: # If LCD is on, then a touch should show the next page
            - lvgl.page.next

image:
  - file: mdi:lightning-bolt
    id: thunderbolt_icon
    resize: 50x50

lvgl:
  touchscreens: my_touchscreen
  log_level: WARN
  color_depth: 16
  bg_color: 0
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: unscii_16
  align: center
  style_definitions:
    - id: meter_style
      text_font: unscii_8
    - id: font_style
      text_font: MONTSERRAT_24
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2 
  on_idle:  # Go back to main page after 15 sec
    - timeout: 15 sec
      then: 
        - lvgl.page.show: main_page
  page_wrap: true
  pages:
    - id: main_page
      widgets:
        - obj: # Meter
            height: 240 # needed to be explicitily defined for my round display to not have weird corder line overlappting gauge
            width: 240
            bg_color: 0
            border_width: 0
            outline_width: 0
            shadow_width: 0
            pad_all: 4
            align: center
            widgets:
              - meter: # Gradient color  arc
                  height: 100%
                  width: 100%
                  border_width: 0
                  outline_width: 0
                  align: center
                  bg_color: 0
                  styles: meter_style
                  scales:
                    angle_range: 240 # sets the total angle to 180 = starts mid left and ends mid right
                    range_to: 150
                    range_from: 0
                    ticks:
                      count: 0

                    indicators:
                      - line:
                          id: power_meter_input
                          width: 10
                          color: 0x0000FF
                          r_mod: 12 #sets line length by this much difference from the scale default radius
                          value: 0
                      - img:
                          id: power_meter_input_img
                      - arc:
                          color: 0x00FF00
                          r_mod: 10 #radius difference from the scale default radius
                          width: 20
                          start_value: 0
                          end_value: !lambda return $section1_end*10;
                      - arc:
                          color: 0xFFFF00 
                          r_mod: 10 #radius difference from the scale default radius
                          width: 20
                          start_value: !lambda return $section1_end*10;
                          end_value: !lambda return $section2_end*10;
                      - arc:
                          color: 0xFF3000
                          r_mod: 10 #radius difference from the scale default radius
                          width: 20
                          start_value: !lambda return $section2_end*10;
                          end_value: !lambda return $section3_end*10;
              - obj: # to erase middle part of meter indicator line
                    height: 180
                    width: 180
                    radius: 90
                    align: center
                    border_width: 0
                    pad_all: 0
                    bg_color: 0x000000
              - label: # gauge lower and higher range indicators
                  styles: font_style
                  text_font: MONTSERRAT_22 # override font size
                  y: 70 #negative = higher
                  x: -70
                  text: "0"
              - label: # gauge lower and higher range indicators
                  styles: font_style
                  text_font: MONTSERRAT_22 # override font size
                  y: -70 #negative = higher
                  x: 0
                  text: $center_label
                  # WIP!
                  #text: !lambda |-
                  #  std::string result = std::to_string(float($section3_end*10/2)/10);
                  #  return result.c_str();
                  # WIP!
              - label:
                  styles: font_style
                  text_font: MONTSERRAT_22 # override font size
                  y: 70 #negative = higher
                  x: 70
                  text: $section3_end
              - label:
                  styles: font_style
                  text_font: MONTSERRAT_40 # override font size
                  id: power_meter_text
                  y: 0
                  text: "? kW"
              - img:
                  src: thunderbolt_icon
                  id: img_thunderbolt
                  align: center
                  img_recolor: 0xFFFF00
                  img_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
                  y: 80
    - id: page1
      height: 240 # needed to be explicitily defined for my round display to not have weird corder line overlappting gauge
      width: 240
      bg_color: 0
      border_width: 0
      outline_width: 0
      shadow_width: 0
      pad_all: 4
      align: center
      widgets:
        - label:
            styles: font_style
            text_font: MONTSERRAT_30 # override font size
            y: -40 #negative = higher
            x: 0
            text: "Until today:"
        - label:
            styles: font_style
            text_font: MONTSERRAT_26 # override font size
            id: kwh_today_text
            y: 0 #negative = higher
            x: 0
            text: "? kWh"
        - label:
            styles: font_style
            text_font: MONTSERRAT_26 # override font size
            id: cost_today_text
            y: 40 #negative = higher
            x: 0
            text: "? eur"
    - id: page2
      height: 240 # needed to be explicitily defined for my round display to not have weird corder line overlappting gauge
      width: 240
      bg_color: 0
      border_width: 0
      outline_width: 0
      shadow_width: 0
      pad_all: 4
      align: center
      widgets:
        - label:
            styles: font_style
            text_font: MONTSERRAT_30 # override font size
            y: -40 #negative = higher
            x: 0
            text: "Months so far:"
        - label:
            styles: font_style
            text_font: MONTSERRAT_26 # override font size
            id: kwh_month_text
            y: 0 #negative = higher
            x: 0
            text: "? kWh"
        - label:
            styles: font_style
            text_font: MONTSERRAT_26 # override font size
            id: cost_month_text
            y: 40 #negative = higher
            x: 0
            text: "? eur"