substitutions:
  name: esp32-bluetooth-proxy-cdf824
  friendly_name: Bluetooth Proxy cdf824
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 3cE1feyMzMhzBr8VZFOUgU1WQ/EW1Rr7dlkHw4UM1xM=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password