substitutions:
  name: esp32-bluetooth-proxy-9d314c
  friendly_name: Bluetooth Proxy 9d314c
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: wNxAPbKOsHjf1SuL4QA3Azx1g+rGVWcp+jVr1Oqg2SI=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
