esphome:
  name: fan-controller
  friendly_name: Fan Controller
  platform: ESP8266
  board: nodemcu

logger:

api:
  encryption:
    key: "FLykuOMwEVU8/6heAc7TFTpwPxy0LaRqWrcONbHFqrw="

ota:
  - platform: esphome
    password: "9d1cd562f1bca962f088d8db081a110a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fan-Controller Fallback Hotspot"
    password: "zD673tFO6i8c"

output:
  - platform: esp8266_pwm
    id: console_fan_speed
    pin: D0
    frequency: "25000 Hz" 
    min_power: 13%
    max_power: 80%
    zero_means_zero: true

switch:
  - platform: gpio
    pin: D6
    id: fan_relay
    name: "Lüfter"