esphome:
  name: fan-controller
  friendly_name: Fan Controller
  platform: ESP8266
  board: nodemcu


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FLykuOMwEVU8/6heAc7TFTpwPxy0LaRqWrcONbHFqrw="

ota:
  - platform: esphome
    password: "9d1cd562f1bca962f088d8db081a110a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan-Controller Fallback Hotspot"
    password: "zD673tFO6i8c"

output:
  - platform: esp8266_pwm
    pin: D0
    frequency: 25000 Hz
    id: pwm1_output
  
  - platform: esp8266_pwm
    pin: D1
    frequency: 25000 Hz
    id: pwm2_output

switch:
  - platform: gpio
    pin: D6
    id: fan_relay
    name: "Lüfter"

fan:
  - platform: speed
    output: pwm1_output
    id: "fan1"
    name: "Fan 1"
    on_turn_on:
    - switch.turn_on: fan_relay
    on_turn_off:
    - switch.turn_off: fan_relay

  - platform: speed
    output: pwm2_output
    id: "fan2"
    name: "Fan 2"
    on_turn_on:
    - switch.turn_on: fan_relay
    on_turn_off:
    - switch.turn_off: fan_relay