esphome:
  name: fan-controller
  friendly_name: Fan Controller
  platform: ESP8266
  board: nodemcu

logger:

api:
  encryption:
    key: "FLykuOMwEVU8/6heAc7TFTpwPxy0LaRqWrcONbHFqrw="

ota:
  - platform: esphome
    password: "9d1cd562f1bca962f088d8db081a110a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fan-Controller Fallback Hotspot"
    password: "zD673tFO6i8c"

output:
  - platform: ledc
    id: console_fan_speed
    pin: D0
    frequency: "25000 Hz" 
    min_power: 13%
    max_power: 80%
    zero_means_zero: true

  - platform: template
    id: proxy_output
    type: float
    write_action:
      lambda: |-
        float write_val = 
          (id(manual_fan_control).state) ?
            id(manual_fan_control).speed / 100.0 : state*1.0;
        id(console_fan_speed).set_level(write_val);
        id(fan_speed_pwm_voltage).publish_state(write_val*100.0);

switch:
  - platform: gpio
    pin: D6
    id: fan_relay
    name: "Lüfter"