esphome:
  name: flur-decke
  friendly_name: Flur Decke

esp32:
  board: nodemcu-32s

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Flur-Decke Fallback Hotspot"
    password: "Hk2Napj7vDri"

captive_portal:
    
switch:
  - platform: gpio
    pin: GPIO33
    id: decke_led_relais
    name: "Decke LED"
    icon: mdi:led-strip-variant

web_server:
    port: 80