substitutions:
  name: home-assistant-voice-09bbe6
  friendly_name: Voice Wohnzimmer
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: zwHAOze63wPhSnG8RPVSe26Jj5ghO7s32QIGwUJY+c0=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
