esphome:
  name: ikea-vindrinktning-wohnzimmer
  friendly_name: IKEA VINDRINKTNING Wohnzimmer

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "qmbdzSEY99+pTJ3AQiDV/aL1aUUhNLFPOosth0DVZwI="

ota:
  - platform: esphome
    password: "25395c7292660668792fc4c957299da8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Ikea-Vindrinktning-Wohnzimmer"
    password: "OoSmpDIluea4"

captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Ikea Vindriktning Wohnzimmer PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10