esphome:
  name: ikea-vindrinktning-buro
  friendly_name: IKEA VINDRINKTNING Büro

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "mA3zYF4YepykAaZaXcqRP5wf/MgMLG0z14s9thLPpNw="

ota:
  - platform: esphome
    password: "31db6e198e99efab65d53e3ce00c1092"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Ikea-Vindrinktning-Buro"
    password: "mpdlto9vi1uh"

captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Ikea Vindriktning Büro PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10