esphome:
  name: ikea-vindrinktning-schlafzimmer
  friendly_name: IKEA VINDRINKTNING Schlafzimmer

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "Txc9uePVSoy4rikaxM/ZszVZQg/J72QgM4Sw453pRWc="

ota:
  - platform: esphome
    password: "c9888224363fed4b9dec8f74de14a3d8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Ikea-Vindrinktning-Schlafzimmer"
    password: "MvXA4IcncQQu"

captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Ikea Vindriktning PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10