esphome:
  name: ikea-vindrinktning-wohnzimmer
  friendly_name: IKEA VINDRINKTNING Wohnzimmer

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "Z9A42tyBvo/GnEVzGAWohQ3e60oZjme1AMyMy6L7F6Y="

ota:
  - platform: esphome
    password: "6afe6f213426ba77b57627d1f155707c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Ikea-Vindrinktning-Wohnzimmer"
    password: "EwmjGeeSqK1U"

captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Ikea Vindriktning PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10