esphome:
  name: ikea-vindrinktning-wohnzimmer
  friendly_name: IKEA VINDRINKTNING Wohnzimmer

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XMAML2LjouAD3JsI5wyjwAXT6S867eUJ+3JowI6HB6c="

ota:
  - platform: esphome
    password: "d05ba639c3d18d14d572eda3d1704783"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.182.1.43

  ap:
    ssid: "Ikea-Vindrinktning-Wohnzimmer"
    password: "QvgjAYIVQtIT"

captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  – platform: pm1006
    pm_2_5:
      name: "Ikea Vindriktning Wohnzimmer PM25"
      filters:
        – sliding_window_moving_average:
            window_size: 10
            send_every: 10  