esphome:
  name: "multi-relais-4x"
  friendly_name: Multi Relais 4x

esp8266:
  board: nodemcu

logger:

api:
  encryption:
    key: "LZ5pTESh9clonjVkfbf/AOxOs0vwgvMy7yZhK9FZk6g="

ota:
  - platform: esphome
    password: "a39c8c3071ec3d0cd101065c00dd3e41"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Multi-Relais-8X Fallback Hotspot"
    password: "gqNrRjmy6I47"

captive_portal:

switch:
  - platform: gpio
    name: "Relay 1"
    pin: D8
  - platform: gpio
    name: "Relay 2"
    pin: D7
  - platform: gpio
    name: "Relay 3"
    pin: D6
  - platform: gpio
    name: "Relay 4"
    pin: D5