esphome:
  name: proxy-wohnzimmer
  friendly_name: proxy-wohnzimmer

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "bZb4jouiuIrl3KuPAsGIShm73a7fIFcR7kD7rOok+xE="

ota:
  password: "a8b6c7eca92656c1d0c999eafe0df828"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: ${name}

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: ble_presence
    mac_address: AC:37:43:77:5F:4C
    name: "ESP32 BLE Presence Google Home Mini"

    