esphome:
  name: proxy-wohnzimmer
  friendly_name: proxy-wohnzimmer

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "bZb4jouiuIrl3KuPAsGIShm73a7fIFcR7kD7rOok+xE="

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: ${name}

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: ble_presence
    mac_address: 4C:E6:C0:F2:D4:03
    name: "iPhone von Florian BLE"

    