esphome:
  name: serverschrank-lufter
  friendly_name: Serverschrank Lüfter

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  logs: 
    climate: ERROR
    dht: WARN

api:
  encryption:
    key: "8NzHAnHJ2a3NLrYTBky9UX4X34dfFUHJlYkYjDeTj3k="

ota:
  - platform: esphome
    password: "d89ed14174d881ecc85f233915e4f017"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Serverschrank-Lufter"
    password: "joPmNsg5rjrn"

captive_portal:

preferences:
  flash_write_interval: 15min

packages:
  base: !include common/base_32.yaml
  ble: !include common/ble_gateway.yaml

wifi:
  manual_ip:
    static_ip: 10.182.1.49

web_server:
  version: 2
  include_internal: true