substitutions:
  name: tagreader-f8c07f
  friendly_name: Tag Reader Kinderzimmer
packages:
  adonno.tag_reader: github://adonno/tagreader/tagreader.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.182.1.220
    gateway: 10.182.1.1
    subnet: 255.255.255.0

ota:
  - platform: esphome
    password: !secret ota_password

switch:
  - platform: restart
    name: "Restart"

captive_portal:
web_server: