substitutions:
  name: upsy-desky-9fb728
  friendly_name: Upsy Desky 9fb728

packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/stock.yaml@v4.0.0

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: WuhQmg8tvTM+cdWaumATBdRJ4Pd++v2rOrU0pq/kjxk=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.182.1.231
    gateway: 10.182.1.1
    subnet: 255.255.255.0
