esphome:
  name: wasserpumpe-balkon
  friendly_name: Wasserpumpe Balkon

esp8266:
  board: nodemcu

# Enable logging
logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wasserpumpe-Balkon"
    password: "wWYM3NUj7Cgb"

captive_portal:
    
switch:
  - platform: gpio
    name: "Pumpe"
    icon: mdi:water-pump
    pin: D1
  - platform: restart
    name: "Restart"