esphome:
  name: wasserhahn-kuche
  friendly_name: Wasserhahn Küche

esp8266:
  board: nodemcu

logger:

api:
  encryption:
    key: "cFRLdhEtSNXYgQvKVW9QLvUce5td5IyMtslTvNjmcR4="

ota:
  password: "345430cb930dc0bc755698c6aed1cbea"

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password

  ap:
    ssid: "Wasserhahn-Kuche"
    password: "utILQGLfKKdk"

captive_portal:

output:
  - platform: gpio
    pin: D6
    id: 'generic_out'
switch:
  - platform: output
    name: "Wasserhahn"
    output: 'generic_out'