homeassistant: true
advanced:
  network_key:
    - 200
    - 61
    - 33
    - 214
    - 14
    - 209
    - 146
    - 85
    - 146
    - 113
    - 84
    - 227
    - 189
    - 18
    - 77
    - 175
  pan_id: 10374
  ext_pan_id:
    - 177
    - 20
    - 58
    - 110
    - 7
    - 164
    - 46
    - 78
mqtt:
  server: mqtt://localhost:1883
  user: mqtt_user
  password: mqtt_pass
frontend:
  port: 8099
